In [39]:
#import statements
import pandas as pd
import matplotlib.pyplot as plt
import subprocess
import numpy as np
import nilearn.image
import nilearn.plotting
import tempfile
import copy
from torch.utils.data import random_split
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from pathlib import Path
import ants
import pydicom
import nibabel as nib
import os
from glob import glob
from tqdm import tqdm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from torchinfo import summary
import nilearn

In [2]:
def dicom_to_adc_map(dicom_dir, output_path=None):
    """
    Convert DICOM files from a directory to a raw DTI ADC map (numpy array or NIfTI).
    
    Parameters:
    -----------
    dicom_dir : str or Path
        Path to directory containing DICOM files
    output_path : str or Path, optional
        If provided, saves as NIfTI file at this path
        
    Returns:
    --------
    adc_map : numpy.ndarray
        3D array of ADC values
    affine : numpy.ndarray
        Affine transformation matrix
    """
    dicom_dir = Path(dicom_dir)
    dicom_files = list(dicom_dir.glob("*.dcm")) + list(dicom_dir.glob("*.DCM"))
    
    if not dicom_files:
        raise ValueError(f"No DICOM files found in {dicom_dir}")
    
    # Read all DICOM files
    dicom_datasets = []
    for dcm_file in dicom_files:
        try:
            ds = pydicom.dcmread(str(dcm_file))
            dicom_datasets.append(ds)
        except Exception as e:
            print(f"Warning: Could not read {dcm_file}: {e}")
            continue
    
    if not dicom_datasets:
        raise ValueError("No valid DICOM files could be read")
    
    # Sort by slice location (ImagePositionPatient[2]) or InstanceNumber
    def get_slice_location(ds):
        if hasattr(ds, 'SliceLocation') and ds.SliceLocation is not None:
            return float(ds.SliceLocation)
        elif hasattr(ds, 'ImagePositionPatient') and ds.ImagePositionPatient is not None:
            return float(ds.ImagePositionPatient[2])
        elif hasattr(ds, 'InstanceNumber') and ds.InstanceNumber is not None:
            return float(ds.InstanceNumber)
        else:
            return 0.0
    
    dicom_datasets.sort(key=get_slice_location)
    
    # Get pixel data and spacing
    pixel_data = []
    for ds in dicom_datasets:
        # Get pixel array (apply rescale slope/intercept if present)
        pixels = ds.pixel_array.astype(np.float32)
        
        # Apply rescale slope and intercept if available
        if hasattr(ds, 'RescaleSlope'):
            pixels = pixels * float(ds.RescaleSlope)
        if hasattr(ds, 'RescaleIntercept'):
            pixels = pixels + float(ds.RescaleIntercept)
        
        pixel_data.append(pixels)
    
    # Stack into 3D array
    adc_map = np.stack(pixel_data, axis=0)  # Shape: (slices, height, width)
    
    # Get voxel spacing and orientation
    first_ds = dicom_datasets[0]
    
    # Pixel spacing
    if hasattr(first_ds, 'PixelSpacing') and first_ds.PixelSpacing:
        pixel_spacing = [float(x) for x in first_ds.PixelSpacing]
    else:
        pixel_spacing = [1.0, 1.0]  # Default
    
    # Slice thickness/spacing
    if hasattr(first_ds, 'SpacingBetweenSlices') and first_ds.SpacingBetweenSlices:
        slice_spacing = float(first_ds.SpacingBetweenSlices)
    elif len(dicom_datasets) > 1:
        # Calculate from slice locations
        slice_locs = [get_slice_location(ds) for ds in dicom_datasets]
        slice_spacing = abs(slice_locs[1] - slice_locs[0]) if len(slice_locs) > 1 else 1.0
    else:
        slice_spacing = 1.0
    
    # Create affine matrix (simple version - may need adjustment based on DICOM orientation)
    affine = np.eye(4)
    affine[0, 0] = pixel_spacing[0]  # x spacing
    affine[1, 1] = pixel_spacing[1]  # y spacing
    affine[2, 2] = slice_spacing     # z spacing
    
    # Get image position if available
    if hasattr(first_ds, 'ImagePositionPatient') and first_ds.ImagePositionPatient:
        affine[:3, 3] = [float(x) for x in first_ds.ImagePositionPatient]
    
    # Save as NIfTI if output path provided
    if output_path:
        nii_img = nib.Nifti1Image(adc_map, affine)
        nib.save(nii_img, str(output_path))
        print(f"Saved ADC map to {output_path}")
        print(f"Shape: {adc_map.shape}, Spacing: {pixel_spacing + [slice_spacing]}")
    
    return adc_map, affine

In [3]:
def dicom_to_t1_mri(dicom_dir, output_path=None):
    """
    Convert T1 MRI DICOM files from a directory to a NIfTI file.
    
    Parameters:
    -----------
    dicom_dir : str or Path
        Path to directory containing DICOM files
    output_path : str or Path, optional
        If provided, saves as NIfTI file at this path
        
    Returns:
    --------
    t1_volume : numpy.ndarray
        3D array of T1 MRI values
    affine : numpy.ndarray
        Affine transformation matrix
    """
    dicom_dir = Path(dicom_dir)
    dicom_files = list(dicom_dir.glob("*.dcm")) + list(dicom_dir.glob("*.DCM"))
    
    if not dicom_files:
        raise ValueError(f"No DICOM files found in {dicom_dir}")
    
    # Read all DICOM files
    dicom_datasets = []
    for dcm_file in dicom_files:
        try:
            ds = pydicom.dcmread(str(dcm_file))
            dicom_datasets.append(ds)
        except Exception as e:
            print(f"Warning: Could not read {dcm_file}: {e}")
            continue
    
    if not dicom_datasets:
        raise ValueError("No valid DICOM files could be read")
    
    # Sort by slice location (ImagePositionPatient[2]) or InstanceNumber
    def get_slice_location(ds):
        if hasattr(ds, 'SliceLocation') and ds.SliceLocation is not None:
            return float(ds.SliceLocation)
        elif hasattr(ds, 'ImagePositionPatient') and ds.ImagePositionPatient is not None:
            return float(ds.ImagePositionPatient[2])
        elif hasattr(ds, 'InstanceNumber') and ds.InstanceNumber is not None:
            return float(ds.InstanceNumber)
        else:
            return 0.0
    
    dicom_datasets.sort(key=get_slice_location)
    
    # Get pixel data and spacing
    pixel_data = []
    for ds in dicom_datasets:
        # Get pixel array (apply rescale slope/intercept if present)
        pixels = ds.pixel_array.astype(np.float32)
        
        # Apply rescale slope and intercept if available
        if hasattr(ds, 'RescaleSlope'):
            pixels = pixels * float(ds.RescaleSlope)
        if hasattr(ds, 'RescaleIntercept'):
            pixels = pixels + float(ds.RescaleIntercept)
        
        pixel_data.append(pixels)
    
    # Handle single 3D DICOM file or stack multiple 2D slices
    if len(pixel_data) == 1 and len(pixel_data[0].shape) == 3:
        # Single DICOM file with 3D volume
        t1_volume = pixel_data[0]
    elif len(pixel_data) > 0:
        # Multiple 2D slices - stack them
        t1_volume = np.stack(pixel_data, axis=0)  # Shape: (slices, height, width)
    else:
        raise ValueError("No valid pixel data found")
    
    # Get voxel spacing and orientation
    first_ds = dicom_datasets[0]
    
    # Pixel spacing
    if hasattr(first_ds, 'PixelSpacing') and first_ds.PixelSpacing:
        pixel_spacing = [float(x) for x in first_ds.PixelSpacing]
    else:
        pixel_spacing = [1.0, 1.0]  # Default
    
    # Slice thickness/spacing
    slice_spacing = 0.0
    if hasattr(first_ds, 'SpacingBetweenSlices') and first_ds.SpacingBetweenSlices:
        slice_spacing = float(first_ds.SpacingBetweenSlices)
    if slice_spacing == 0.0 and len(dicom_datasets) > 1:
        slice_locs = [get_slice_location(ds) for ds in dicom_datasets]
        if len(slice_locs) > 1:
            slice_spacing = abs(slice_locs[1] - slice_locs[0])
    if slice_spacing == 0.0 and hasattr(first_ds, 'SliceThickness') and first_ds.SliceThickness:
        slice_spacing = float(first_ds.SliceThickness)
    if slice_spacing == 0.0:
        if hasattr(first_ds, 'PerFrameFunctionalGroupsSequence'):
            pfg = first_ds.PerFrameFunctionalGroupsSequence
            if len(pfg) > 1:
                try:
                    pos0 = pfg[0].PlanePositionSequence[0].ImagePositionPatient
                    pos1 = pfg[1].PlanePositionSequence[0].ImagePositionPatient
                    slice_spacing = abs(float(pos1[2]) - float(pos0[2]))
                except (AttributeError, IndexError):
                    pass
    if slice_spacing == 0.0:
        slice_spacing = pixel_spacing[0]
    
    # Create affine matrix (simple version - may need adjustment based on DICOM orientation)
    affine = np.eye(4)
    affine[0, 0] = pixel_spacing[0]  # x spacing
    affine[1, 1] = pixel_spacing[1]  # y spacing
    affine[2, 2] = slice_spacing     # z spacing
    
    # Get image position if available
    if hasattr(first_ds, 'ImagePositionPatient') and first_ds.ImagePositionPatient:
        affine[:3, 3] = [float(x) for x in first_ds.ImagePositionPatient]
    
    # Save as NIfTI if output path provided
    if output_path:
        nii_img = nib.Nifti1Image(t1_volume, affine)
        nib.save(nii_img, str(output_path))
        print(f"Saved T1 MRI to {output_path}")
        print(f"Shape: {t1_volume.shape}, Spacing: {pixel_spacing + [slice_spacing]}")
    
    return t1_volume, affine

In [9]:
# Process all I* folders in t1_mri_dcm and save to t1_mri_raw
t1_base_dir = Path("model_data/adni/t1_long_data/t1_long_dcm/")
t1_output_dir = Path("model_data/adni/t1_long_data/t1_long_raw")

# Collect all I* folders that contain DICOM files
t1_i_folders = [f for f in t1_base_dir.rglob("I*") 
                if f.is_dir() and (any(f.glob("*.dcm")) or any(f.glob("*.DCM")))]

# Initialize counters
t1_processed = 0
t1_errors = 0

In [10]:
# Process each folder with progress bar
for i_folder in tqdm(t1_i_folders, desc="Processing T1 MRI DICOM folders"):
    try:
        # Extract image_id (the I* folder name, e.g., I1593283)
        image_id = i_folder.name
        
        # Extract subject_id from the relative path
        # The structure is: t1_mri_dcm/[subject_id]/.../I[image_id]
        relative_path = i_folder.relative_to(t1_base_dir)
        subject_id = relative_path.parts[0]  # First part is the subject_id
        
        # Create output filename: I[image_id]_[subject_id].nii
        output_filename = f"{image_id}_{subject_id}.nii"
        output_path = t1_output_dir / output_filename
        
        # Skip if already exists
        if output_path.exists():
            continue
        
        # Convert DICOM to T1 MRI NIfTI
        t1_volume, affine = dicom_to_t1_mri(i_folder, output_path)
        t1_processed += 1
        
    except Exception as e:
        print(f"\nError processing {i_folder}: {e}")
        t1_errors += 1
        continue

print(f"\nT1 MRI Processing complete!")
print(f"Successfully processed: {t1_processed}")
print(f"Errors: {t1_errors}")

Processing T1 MRI DICOM folders:   0%|          | 1/802 [00:00<07:16,  1.84it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1304390_003_S_6014.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   0%|          | 2/802 [00:00<05:25,  2.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I965015_003_S_6014.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   0%|          | 3/802 [00:01<05:04,  2.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1564163_003_S_6014.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   0%|          | 4/802 [00:01<05:04,  2.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I399997_130_S_4352.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:   1%|          | 5/802 [00:01<04:32,  2.93it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892709_011_S_4547.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.9999999999960067]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10461508_016_S_6789.nii
Shape: (128, 256, 240), Spacing: [1.0546875, 1.0546875, 1.2000000476837]

Processing T1 MRI DICOM folders:   1%|          | 7/802 [00:02<03:50,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I734494_137_S_4631.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:   1%|          | 8/802 [00:02<03:48,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1155911_022_S_2263.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   1%|          | 9/802 [00:02<03:34,  3.69it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1430346_022_S_2263.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   1%|          | 10/802 [00:03<03:49,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I958011_020_S_6185.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   1%|▏         | 11/802 [00:03<03:46,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1278640_020_S_6185.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   1%|▏         | 12/802 [00:03<04:07,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1117156_020_S_6185.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 13/802 [00:04<03:57,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1254386_014_S_6831.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 14/802 [00:04<03:49,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I938292_033_S_5198.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 15/802 [00:04<03:51,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1072872_033_S_5198.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 16/802 [00:04<03:42,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1519772_033_S_5198.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 17/802 [00:05<03:46,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1258040_033_S_5198.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 18/802 [00:05<03:45,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1246020_003_S_6479.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 19/802 [00:05<03:36,  3.61it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I872948_141_S_4160.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   2%|▏         | 20/802 [00:06<03:45,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1028398_141_S_4160.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 21/802 [00:06<03:38,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10302840_016_S_6773.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999284744]

Processing T1 MRI DICOM folders:   3%|▎         | 22/802 [00:06<03:30,  3.70it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1229464_141_S_6061.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 23/802 [00:06<03:40,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1116406_141_S_6061.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 24/802 [00:07<03:33,  3.64it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I887923_141_S_6061.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 25/802 [00:07<03:45,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I974714_141_S_6253.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 26/802 [00:07<03:39,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1331108_141_S_6253.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 27/802 [00:08<03:42,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1233982_068_S_4332.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   3%|▎         | 28/802 [00:08<03:56,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1033744_068_S_4332.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0000000000039933]

Processing T1 MRI DICOM folders:   4%|▎         | 29/802 [00:08<03:55,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I874427_068_S_4332.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   4%|▎         | 30/802 [00:09<04:25,  2.91it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1348596_168_S_6233.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   4%|▍         | 31/802 [00:09<04:14,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I968225_168_S_6233.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   4%|▍         | 32/802 [00:09<04:23,  2.92it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I394173_130_S_2403.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:   4%|▍         | 33/802 [00:10<04:24,  2.91it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10461505_016_S_6926.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999284744]

Processing T1 MRI DICOM folders:   4%|▍         | 34/802 [00:10<03:58,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I398667_137_S_4299.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826699934]

Processing T1 MRI DICOM folders:   4%|▍         | 35/802 [00:10<03:46,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I632429_036_S_4430.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:   4%|▍         | 36/802 [00:10<03:54,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1022130_128_S_0205.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▍         | 37/802 [00:11<03:39,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I424035_009_S_4612.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:   5%|▍         | 38/802 [00:11<03:53,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1295865_168_S_6851.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▍         | 39/802 [00:11<03:40,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1591145_070_S_7078.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▍         | 40/802 [00:12<03:39,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I899030_168_S_6064.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▌         | 41/802 [00:12<03:38,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1045204_033_S_6572.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▌         | 42/802 [00:12<03:24,  3.71it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1345109_033_S_6572.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▌         | 43/802 [00:12<03:30,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1233828_033_S_6572.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   5%|▌         | 44/802 [00:13<03:18,  3.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1637423_033_S_6572.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   6%|▌         | 45/802 [00:13<03:44,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I594101_018_S_4399.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:   6%|▌         | 46/802 [00:13<03:45,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1300003_168_S_6860.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   6%|▌         | 47/802 [00:14<03:42,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I923016_114_S_6057.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   6%|▌         | 48/802 [00:14<03:27,  3.64it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I648428_137_S_4466.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:   6%|▌         | 49/802 [00:14<03:41,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1069491_011_S_6618.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   6%|▌         | 50/802 [00:14<03:40,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1546250_012_S_6760.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.9999999999960067]

Processing T1 MRI DICOM folders:   6%|▋         | 51/802 [00:15<03:28,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I474657_041_S_5078.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:   6%|▋         | 52/802 [00:15<03:35,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I361248_099_S_4480.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982660998]

Processing T1 MRI DICOM folders:   7%|▋         | 53/802 [00:15<03:22,  3.69it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I507338_137_S_4862.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:   7%|▋         | 54/802 [00:16<03:21,  3.71it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1029584_020_S_6513.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   7%|▋         | 55/802 [00:16<03:30,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1329968_020_S_6513.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   7%|▋         | 56/802 [00:16<03:23,  3.66it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1224869_020_S_6513.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   7%|▋         | 57/802 [00:16<03:34,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1488487_116_S_6775.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   7%|▋         | 58/802 [00:17<03:30,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1332591_116_S_6775.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   7%|▋         | 59/802 [00:17<03:26,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1226101_116_S_6775.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   7%|▋         | 60/802 [00:17<03:42,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I949029_032_S_1169.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 61/802 [00:18<03:35,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1174541_032_S_6728.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 62/802 [00:18<03:37,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1611592_033_S_6976.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 63/802 [00:18<03:25,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10245972_033_S_6976.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 64/802 [00:18<03:15,  3.78it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1463003_033_S_6976.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 65/802 [00:19<03:37,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1157199_032_S_6717.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 66/802 [00:19<03:31,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I895056_022_S_6069.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 67/802 [00:19<03:41,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1485104_022_S_6069.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   8%|▊         | 68/802 [00:20<03:34,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1142366_022_S_6069.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   9%|▊         | 69/802 [00:20<03:34,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1083042_003_S_6644.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   9%|▊         | 70/802 [00:20<03:42,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I982444_116_S_4483.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   9%|▉         | 71/802 [00:21<03:58,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I511791_053_S_5272.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:   9%|▉         | 72/802 [00:21<04:12,  2.89it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I569603_019_S_4367.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:   9%|▉         | 73/802 [00:21<03:51,  3.15it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I315479_099_S_4086.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:   9%|▉         | 74/802 [00:22<04:04,  2.98it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892771_168_S_6062.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   9%|▉         | 75/802 [00:22<03:55,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1280182_168_S_6062.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:   9%|▉         | 76/802 [00:22<03:49,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1296556_168_S_6634.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|▉         | 77/802 [00:23<03:59,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1411687_168_S_6634.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|▉         | 78/802 [00:23<03:52,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1081492_168_S_6634.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|▉         | 79/802 [00:23<04:04,  2.96it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10240800_168_S_6634.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|▉         | 80/802 [00:24<03:53,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I919448_035_S_4114.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|█         | 81/802 [00:24<04:00,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I900796_168_S_6065.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|█         | 82/802 [00:24<03:51,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1609624_168_S_6065.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|█         | 83/802 [00:24<03:42,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1284408_168_S_6065.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  10%|█         | 84/802 [00:25<03:38,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I356446_128_S_2130.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  11%|█         | 85/802 [00:25<03:35,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I925573_168_S_6098.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  11%|█         | 86/802 [00:25<03:37,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1060218_109_S_6376.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  11%|█         | 87/802 [00:26<03:56,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I552099_006_S_0731.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  11%|█         | 88/802 [00:26<03:50,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I415615_031_S_2233.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  11%|█         | 89/802 [00:26<03:54,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I989320_002_S_1261.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  11%|█         | 90/802 [00:27<03:35,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I647828_036_S_4491.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  11%|█▏        | 91/802 [00:27<03:41,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1036017_114_S_5047.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  11%|█▏        | 92/802 [00:27<03:36,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I874809_037_S_6046.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 93/802 [00:28<03:50,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I948826_035_S_6156.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 94/802 [00:28<03:36,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1552295_033_S_6266.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 95/802 [00:28<03:22,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1320538_033_S_6266.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 96/802 [00:28<03:25,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I971748_033_S_6266.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 97/802 [00:29<03:27,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1267882_068_S_0473.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 98/802 [00:29<03:25,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I932015_068_S_0473.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  12%|█▏        | 99/802 [00:29<03:32,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I618010_130_S_4415.nii
Shape: (140, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  12%|█▏        | 100/802 [00:30<03:30,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1058029_033_S_0734.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 101/802 [00:30<03:17,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I919238_033_S_0734.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 102/802 [00:30<03:42,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I944772_168_S_6121.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 103/802 [00:31<03:29,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1584529_016_S_6839.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  13%|█▎        | 104/802 [00:31<03:34,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1151639_070_S_6229.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 105/802 [00:31<03:25,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1427101_070_S_6229.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 106/802 [00:31<03:18,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1564138_070_S_6229.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 107/802 [00:32<03:28,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I969035_070_S_6229.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  13%|█▎        | 108/802 [00:32<03:17,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I445549_009_S_0751.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:  14%|█▎        | 109/802 [00:32<03:15,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I902659_007_S_4488.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▎        | 110/802 [00:33<03:31,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I915825_037_S_6083.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▍        | 111/802 [00:33<03:22,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1116728_036_S_6088.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▍        | 112/802 [00:33<03:38,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I913423_068_S_2315.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▍        | 113/802 [00:34<03:35,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1585896_068_S_2315.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▍        | 114/802 [00:34<03:30,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1346204_068_S_2315.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▍        | 115/802 [00:34<03:37,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I945134_168_S_6128.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  14%|█▍        | 116/802 [00:34<03:26,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1426128_014_S_6920.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  15%|█▍        | 117/802 [00:35<03:39,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I950885_035_S_6160.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.999999999998991]

Processing T1 MRI DICOM folders:  15%|█▍        | 118/802 [00:35<03:27,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1295274_032_S_6855.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  15%|█▍        | 119/802 [00:35<03:36,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1259263_032_S_6600.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  15%|█▍        | 120/802 [00:36<03:25,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1061844_032_S_6600.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  15%|█▌        | 121/802 [00:36<03:12,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I666409_135_S_5113.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826699934]

Processing T1 MRI DICOM folders:  15%|█▌        | 122/802 [00:36<03:17,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1576364_041_S_6786.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  15%|█▌        | 123/802 [00:37<03:11,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I951357_014_S_6148.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  15%|█▌        | 124/802 [00:37<03:14,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1378351_068_S_2187.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.9999999999949978]

Processing T1 MRI DICOM folders:  16%|█▌        | 125/802 [00:37<03:30,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892784_068_S_2187.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  16%|█▌        | 126/802 [00:37<03:28,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1238877_068_S_2187.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  16%|█▌        | 127/802 [00:38<03:39,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1036857_068_S_2187.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  16%|█▌        | 128/802 [00:38<03:35,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I998432_168_S_6371.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  16%|█▌        | 129/802 [00:39<03:42,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10248336_168_S_6371.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  16%|█▌        | 130/802 [00:39<03:33,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1352191_168_S_6371.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  16%|█▋        | 131/802 [00:39<03:44,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I761004_130_S_4817.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  16%|█▋        | 132/802 [00:39<03:29,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1558064_011_S_7048.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 133/802 [00:40<03:36,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1192854_941_S_6054.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 134/802 [00:40<03:20,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1028361_109_S_6406.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 135/802 [00:40<03:19,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1084921_033_S_6497.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 136/802 [00:41<03:04,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1175032_033_S_6497.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 137/802 [00:41<03:01,  3.67it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1490997_014_S_6522.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 138/802 [00:41<03:11,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1037958_014_S_6522.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 139/802 [00:41<03:04,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1241179_014_S_6522.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  17%|█▋        | 140/802 [00:42<03:05,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I849901_032_S_5289.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  18%|█▊        | 141/802 [00:42<03:13,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I996840_032_S_5289.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  18%|█▊        | 142/802 [00:42<03:15,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1174915_032_S_5289.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  18%|█▊        | 143/802 [00:43<03:31,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I639535_006_S_4485.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  18%|█▊        | 144/802 [00:43<03:33,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I361274_099_S_4565.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:  18%|█▊        | 145/802 [00:43<03:22,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1012896_003_S_6307.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  18%|█▊        | 146/802 [00:44<03:29,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1639974_003_S_6307.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  18%|█▊        | 147/802 [00:44<03:23,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1205679_003_S_6307.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  18%|█▊        | 148/802 [00:44<03:23,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I442430_041_S_4874.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  19%|█▊        | 149/802 [00:45<03:18,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1083056_003_S_1122.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  19%|█▊        | 150/802 [00:45<03:12,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1020423_003_S_1122.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  19%|█▉        | 151/802 [00:45<03:23,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1162367_003_S_1122.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  19%|█▉        | 152/802 [00:45<03:14,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I853501_003_S_1122.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  19%|█▉        | 153/802 [00:46<03:17,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I727731_036_S_4715.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  19%|█▉        | 154/802 [00:46<03:07,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I929044_023_S_1190.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  19%|█▉        | 155/802 [00:46<03:08,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1075536_941_S_4100.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  19%|█▉        | 156/802 [00:47<03:15,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I970020_114_S_6113.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|█▉        | 157/802 [00:47<03:01,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1335384_114_S_6113.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|█▉        | 158/802 [00:47<03:22,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I495118_130_S_2373.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  20%|█▉        | 159/802 [00:48<03:29,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1018889_116_S_6458.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|█▉        | 160/802 [00:48<03:16,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I961824_141_S_6178.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|██        | 161/802 [00:48<03:20,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1299107_141_S_6178.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|██        | 162/802 [00:48<03:10,  3.36it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1136571_141_S_6178.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|██        | 163/802 [00:49<02:59,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1634180_013_S_7103.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  20%|██        | 164/802 [00:49<03:08,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1450130_022_S_6716.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 0.999999999998991]

Processing T1 MRI DICOM folders:  21%|██        | 165/802 [00:49<03:01,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1329955_022_S_6716.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██        | 166/802 [00:50<02:58,  3.56it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1162708_022_S_6716.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██        | 167/802 [00:50<03:11,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1018165_941_S_6052.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██        | 168/802 [00:50<03:03,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1450061_014_S_6944.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██        | 169/802 [00:50<03:05,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1262194_033_S_1016.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██        | 170/802 [00:51<02:53,  3.64it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I943663_033_S_1016.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██▏       | 171/802 [00:51<02:49,  3.71it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1334631_070_S_6886.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  21%|██▏       | 172/802 [00:51<03:08,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I905421_012_S_4188.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 173/802 [00:52<03:10,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1610176_168_S_6180.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 174/802 [00:52<03:21,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1151926_168_S_6180.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 175/802 [00:52<03:16,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I958678_168_S_6180.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 176/802 [00:53<03:23,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1359777_168_S_6180.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 177/802 [00:53<03:10,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1064839_114_S_6524.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1653108_114_S_6524.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 179/802 [00:53<03:03,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1448643_003_S_6954.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  22%|██▏       | 180/802 [00:54<02:57,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1481579_014_S_6988.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  23%|██▎       | 181/802 [00:54<02:52,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I339965_099_S_2063.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  23%|██▎       | 182/802 [00:54<03:03,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1147981_032_S_6699.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  23%|██▎       | 183/802 [00:55<03:19,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I460838_031_S_4021.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  23%|██▎       | 184/802 [00:55<03:12,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1167318_168_S_6142.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  23%|██▎       | 185/802 [00:55<03:21,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1299334_168_S_6142.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  23%|██▎       | 186/802 [00:56<03:11,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I946980_168_S_6142.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  23%|██▎       | 187/802 [00:56<03:02,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1483860_003_S_6996.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  23%|██▎       | 188/802 [00:56<03:18,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I495048_100_S_5091.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  24%|██▎       | 189/802 [00:57<03:19,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1207265_141_S_6787.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  24%|██▎       | 190/802 [00:57<03:17,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1067189_012_S_6073.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  24%|██▍       | 191/802 [00:57<03:25,  2.97it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I908586_012_S_6073.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  24%|██▍       | 192/802 [00:58<03:36,  2.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I580989_018_S_4400.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  24%|██▍       | 193/802 [00:58<03:17,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I640880_009_S_4388.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  24%|██▍       | 194/802 [00:58<03:26,  2.94it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I466107_018_S_2155.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  24%|██▍       | 195/802 [00:59<03:15,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1002374_014_S_6366.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  24%|██▍       | 196/802 [00:59<03:18,  3.05it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I850396_037_S_0303.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▍       | 197/802 [00:59<03:19,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I913435_068_S_4061.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▍       | 198/802 [01:00<03:26,  2.92it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1260279_068_S_4061.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▍       | 199/802 [01:00<03:12,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1591455_014_S_7072.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▍       | 200/802 [01:00<03:09,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1146857_024_S_6005.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▌       | 201/802 [01:01<03:10,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I873879_041_S_4037.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.199999982659989]

Processing T1 MRI DICOM folders:  25%|██▌       | 202/802 [01:01<02:58,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1069428_116_S_6624.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▌       | 203/802 [01:01<03:13,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1185293_024_S_6033.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  25%|██▌       | 204/802 [01:02<03:32,  2.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1304737_168_S_6151.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▌       | 205/802 [01:02<03:23,  2.94it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1612776_168_S_6151.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▌       | 206/802 [01:02<03:26,  2.88it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I947540_168_S_6151.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▌       | 207/802 [01:03<03:13,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I949429_141_S_2333.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▌       | 208/802 [01:03<03:15,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1270525_141_S_2333.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▌       | 209/802 [01:03<03:04,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1473903_141_S_2333.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▌       | 210/802 [01:03<02:55,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1100469_141_S_2333.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▋       | 211/802 [01:04<03:05,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I812263_037_S_4302.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  26%|██▋       | 212/802 [01:04<03:15,  3.01it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I569632_002_S_0413.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  27%|██▋       | 213/802 [01:04<03:03,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1485506_116_S_0382.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  27%|██▋       | 214/802 [01:05<02:53,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1037249_116_S_0382.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  27%|██▋       | 215/802 [01:05<03:10,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I870102_037_S_6031.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  27%|██▋       | 216/802 [01:05<02:59,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1020512_114_S_6368.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  27%|██▋       | 217/802 [01:06<03:08,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I916119_007_S_4637.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  27%|██▋       | 218/802 [01:06<03:00,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I984325_109_S_6220.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  27%|██▋       | 219/802 [01:06<03:13,  3.01it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I581890_130_S_4294.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  27%|██▋       | 220/802 [01:07<03:09,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1040031_168_S_6561.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  28%|██▊       | 221/802 [01:07<03:06,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I955473_033_S_4176.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  28%|██▊       | 222/802 [01:07<02:56,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1440034_014_S_6935.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  28%|██▊       | 223/802 [01:08<03:13,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I350833_129_S_4369.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  28%|██▊       | 224/802 [01:08<03:02,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I858504_141_S_1378.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  28%|██▊       | 225/802 [01:08<03:04,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1161827_141_S_1378.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  28%|██▊       | 226/802 [01:09<02:56,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I957745_011_S_0021.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  28%|██▊       | 227/802 [01:09<02:44,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I574539_137_S_4351.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:  28%|██▊       | 228/802 [01:09<02:51,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I982856_109_S_6218.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▊       | 229/802 [01:09<02:53,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1638162_168_S_6754.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▊       | 230/802 [01:10<03:05,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1181679_168_S_6754.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▉       | 232/802 [01:10<02:24,  3.95it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1343923_168_S_6754.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1327456_177_S_6335.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▉       | 233/802 [01:10<02:28,  3.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1535666_003_S_5130.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▉       | 234/802 [01:11<02:45,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1263339_003_S_5130.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▉       | 235/802 [01:11<02:44,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1416081_168_S_6908.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  29%|██▉       | 236/802 [01:11<02:59,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I813811_100_S_4556.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  30%|██▉       | 237/802 [01:12<03:02,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I983428_020_S_6282.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  30%|██▉       | 238/802 [01:12<02:52,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1080321_114_S_6597.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  30%|██▉       | 239/802 [01:12<02:53,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1344334_033_S_6889.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  30%|██▉       | 240/802 [01:13<02:42,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1508469_033_S_6889.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  30%|███       | 241/802 [01:13<02:36,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1630167_033_S_6889.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  30%|███       | 242/802 [01:13<02:49,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1370464_137_S_4536.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  30%|███       | 243/802 [01:13<02:37,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I650296_137_S_4536.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  30%|███       | 244/802 [01:14<02:35,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1224468_014_S_4401.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███       | 245/802 [01:14<02:50,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I907767_014_S_4401.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███       | 246/802 [01:14<02:44,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1556676_014_S_4401.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███       | 247/802 [01:15<02:59,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I812646_100_S_1286.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  31%|███       | 248/802 [01:15<02:59,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1116890_114_S_2392.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███       | 249/802 [01:15<02:50,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I909791_114_S_2392.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███       | 250/802 [01:16<02:48,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1267018_114_S_2392.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███▏      | 251/802 [01:16<02:38,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I972151_109_S_4380.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  31%|███▏      | 252/802 [01:16<02:40,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I992566_003_S_5154.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  32%|███▏      | 253/802 [01:17<02:49,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1589384_003_S_5154.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  32%|███▏      | 255/802 [01:17<02:12,  4.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1154285_011_S_6714.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I767920_018_S_4868.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  32%|███▏      | 256/802 [01:17<02:24,  3.78it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I638463_135_S_4489.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826649912]

Processing T1 MRI DICOM folders:  32%|███▏      | 257/802 [01:18<02:24,  3.78it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1017005_116_S_6428.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  32%|███▏      | 258/802 [01:18<02:22,  3.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1181047_116_S_6428.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  32%|███▏      | 259/802 [01:18<02:31,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1241872_020_S_5203.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  32%|███▏      | 260/802 [01:18<02:30,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1086072_020_S_5203.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  33%|███▎      | 261/802 [01:19<02:30,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I946297_020_S_5203.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  33%|███▎      | 262/802 [01:19<02:34,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I310636_128_S_2002.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  33%|███▎      | 263/802 [01:19<02:30,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1592044_014_S_7080.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  33%|███▎      | 264/802 [01:20<02:40,  3.36it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1132797_011_S_4278.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  33%|███▎      | 265/802 [01:20<02:36,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I940882_011_S_4278.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.9999999999960067]

Processing T1 MRI DICOM folders:  33%|███▎      | 266/802 [01:20<02:33,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1501111_011_S_4278.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  33%|███▎      | 267/802 [01:20<02:46,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1281631_011_S_4278.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  33%|███▎      | 268/802 [01:21<02:45,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892723_068_S_4067.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▎      | 269/802 [01:21<02:50,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I966803_014_S_6199.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▎      | 270/802 [01:21<02:40,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1166993_014_S_6199.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▍      | 271/802 [01:22<02:35,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1050345_002_S_4229.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▍      | 272/802 [01:22<02:41,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I906797_002_S_4229.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▍      | 273/802 [01:22<02:39,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I981036_032_S_6279.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▍      | 274/802 [01:23<02:51,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1181388_032_S_6279.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▍      | 275/802 [01:23<02:38,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1281495_033_S_4179.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  34%|███▍      | 276/802 [01:23<02:29,  3.52it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I957065_033_S_4179.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  35%|███▍      | 277/802 [01:24<02:37,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1423364_003_S_6915.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  35%|███▍      | 278/802 [01:24<02:51,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I561261_006_S_0498.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  35%|███▍      | 279/802 [01:24<02:39,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I983404_109_S_6219.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  35%|███▍      | 280/802 [01:25<02:52,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I742548_130_S_5175.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  35%|███▌      | 281/802 [01:25<02:49,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1022960_109_S_6221.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  35%|███▌      | 282/802 [01:25<02:41,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1427086_003_S_6924.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  35%|███▌      | 283/802 [01:25<02:29,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1280292_033_S_4177.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  35%|███▌      | 284/802 [01:26<02:34,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I956358_033_S_4177.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▌      | 285/802 [01:26<02:37,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1444117_168_S_6938.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▌      | 286/802 [01:26<02:44,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1160987_003_S_6258.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▌      | 287/802 [01:27<02:38,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1429976_003_S_6258.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▌      | 288/802 [01:27<02:36,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I973293_003_S_6258.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▌      | 289/802 [01:27<02:45,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1574950_003_S_6258.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▌      | 290/802 [01:28<02:45,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1667256_168_S_6875.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▋      | 291/802 [01:28<02:53,  2.94it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1319217_168_S_6875.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  36%|███▋      | 292/802 [01:28<02:50,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I916365_168_S_6049.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 293/802 [01:29<02:56,  2.88it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1348108_168_S_6049.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 294/802 [01:29<02:49,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I927511_037_S_4028.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 295/802 [01:29<02:46,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1304804_168_S_6085.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 296/802 [01:30<02:55,  2.89it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I916399_168_S_6085.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 297/802 [01:30<02:49,  2.98it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10236670_168_S_6085.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 298/802 [01:30<02:48,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1469350_013_S_6970.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  37%|███▋      | 299/802 [01:31<02:40,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892212_002_S_6066.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.999999999998991]

Processing T1 MRI DICOM folders:  37%|███▋      | 300/802 [01:31<02:34,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1185102_003_S_6260.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 301/802 [01:31<02:40,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1001084_003_S_6260.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 302/802 [01:32<02:36,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1590171_003_S_6260.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 303/802 [01:32<02:35,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1218138_013_S_6725.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 304/802 [01:32<02:33,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I925944_007_S_4387.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 305/802 [01:33<03:13,  2.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I983641_168_S_6281.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 306/802 [01:33<03:15,  2.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I818409_037_S_4214.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 307/802 [01:34<03:14,  2.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I926915_014_S_6087.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  38%|███▊      | 308/802 [01:34<03:06,  2.65it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1582530_003_S_6256.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  39%|███▊      | 309/802 [01:34<02:55,  2.81it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I973278_003_S_6256.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  39%|███▊      | 310/802 [01:35<02:49,  2.90it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1629558_013_S_7097.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  39%|███▉      | 311/802 [01:35<02:41,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1275415_168_S_6843.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  39%|███▉      | 313/802 [01:35<02:23,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I912458_003_S_1074.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I384100_003_S_1074.nii
Shape: (160, 192, 192), Spacing: [1.25, 1.25, 1.1999999999979991]

Processing T1 MRI DICOM folders:  39%|███▉      | 314/802 [01:36<02:22,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1252848_003_S_4350.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  39%|███▉      | 315/802 [01:36<02:26,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I344532_128_S_2123.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  39%|███▉      | 316/802 [01:36<02:26,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1195083_024_S_4084.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|███▉      | 317/802 [01:37<02:33,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1236269_168_S_6817.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|███▉      | 318/802 [01:37<02:31,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1240482_168_S_6828.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|███▉      | 319/802 [01:37<02:39,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1561917_168_S_6828.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|███▉      | 320/802 [01:38<02:37,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1398870_168_S_6828.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|████      | 321/802 [01:38<02:44,  2.93it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I373705_031_S_4721.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  40%|████      | 322/802 [01:38<02:37,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1041482_011_S_6465.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|████      | 323/802 [01:39<02:39,  3.01it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1193331_011_S_6465.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  40%|████      | 324/802 [01:39<02:29,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1254307_003_S_6833.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████      | 325/802 [01:39<02:29,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I357842_128_S_4842.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:  41%|████      | 326/802 [01:39<02:22,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1026224_109_S_6300.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████      | 327/802 [01:40<02:17,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1028485_141_S_1052.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████      | 328/802 [01:40<02:26,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I842509_141_S_1052.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████      | 329/802 [01:40<02:21,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1478685_141_S_1052.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████      | 330/802 [01:41<02:17,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1146964_141_S_1052.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████▏     | 331/802 [01:41<02:23,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1017836_002_S_6456.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  41%|████▏     | 332/802 [01:41<02:22,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1175398_036_S_2380.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  42%|████▏     | 333/802 [01:42<02:33,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10929110_168_S_6821.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  42%|████▏     | 334/802 [01:42<02:26,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1390871_168_S_6821.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  42%|████▏     | 336/802 [01:43<02:16,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1244550_168_S_6821.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I26217_128_S_0272.nii
Shape: (160, 192, 192), Spacing: [1.25, 1.25, 1.1999999999999886]

Processing T1 MRI DICOM folders:  42%|████▏     | 337/802 [01:43<01:51,  4.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I655568_018_S_4313.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  42%|████▏     | 338/802 [01:43<01:55,  4.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I533671_123_S_4170.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  42%|████▏     | 339/802 [01:43<02:05,  3.69it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I508115_041_S_4143.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982660998]

Processing T1 MRI DICOM folders:  42%|████▏     | 340/802 [01:44<02:06,  3.66it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I883190_141_S_6042.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  43%|████▎     | 341/802 [01:44<02:21,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I914397_012_S_4643.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  43%|████▎     | 342/802 [01:44<02:16,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1176879_116_S_6750.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  43%|████▎     | 343/802 [01:44<02:13,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1477605_116_S_6750.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  43%|████▎     | 344/802 [01:45<02:27,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I435779_027_S_4757.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  43%|████▎     | 345/802 [01:45<02:34,  2.96it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I722888_006_S_4713.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  43%|████▎     | 346/802 [01:46<02:31,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1475674_153_S_6679.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  43%|████▎     | 347/802 [01:46<02:20,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1061955_109_S_6364.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  43%|████▎     | 348/802 [01:46<02:26,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I905391_007_S_5265.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▎     | 349/802 [01:46<02:25,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1116800_012_S_5157.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▎     | 350/802 [01:47<02:35,  2.90it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I491256_002_S_1280.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  44%|████▍     | 351/802 [01:47<02:34,  2.93it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1618413_003_S_6268.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▍     | 352/802 [01:47<02:27,  3.05it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1494007_003_S_6268.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▍     | 353/802 [01:48<02:24,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1196215_003_S_6268.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▍     | 354/802 [01:48<02:28,  3.01it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1005884_003_S_6268.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▍     | 355/802 [01:48<02:18,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1022985_109_S_6363.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  44%|████▍     | 356/802 [01:49<02:19,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I663667_135_S_4598.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  45%|████▍     | 357/802 [01:49<02:13,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1047619_114_S_6429.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  45%|████▍     | 358/802 [01:49<02:06,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I499446_009_S_5176.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:  45%|████▍     | 359/802 [01:50<02:16,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I974338_003_S_6257.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  45%|████▍     | 360/802 [01:50<02:17,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1179769_024_S_4674.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  45%|████▌     | 361/802 [01:50<02:25,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I964899_035_S_0555.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  45%|████▌     | 362/802 [01:51<02:25,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1071932_012_S_5195.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  45%|████▌     | 363/802 [01:51<02:34,  2.85it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1318202_168_S_6873.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  45%|████▌     | 364/802 [01:51<02:28,  2.95it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1211451_036_S_6316.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▌     | 365/802 [01:52<02:22,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1382659_168_S_6619.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▌     | 366/802 [01:52<03:07,  2.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1069896_168_S_6619.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▌     | 367/802 [01:53<02:58,  2.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1267220_168_S_6619.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▌     | 368/802 [01:53<02:57,  2.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1578905_003_S_6259.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▌     | 369/802 [01:54<03:16,  2.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I977365_003_S_6259.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▌     | 370/802 [01:54<03:14,  2.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1029553_116_S_6537.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▋     | 371/802 [01:54<03:03,  2.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1021530_002_S_6404.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  46%|████▋     | 372/802 [01:55<02:56,  2.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1346152_168_S_6413.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 373/802 [01:55<03:00,  2.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1008547_168_S_6413.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 374/802 [01:56<02:52,  2.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1318866_168_S_6874.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 375/802 [01:56<02:51,  2.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1667508_168_S_6874.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 376/802 [01:56<02:47,  2.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1043769_003_S_6490.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 377/802 [01:57<02:37,  2.71it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I988474_052_S_4944.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 378/802 [01:57<02:32,  2.78it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1031290_070_S_6542.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 379/802 [01:57<02:20,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1054709_114_S_6487.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  47%|████▋     | 380/802 [01:58<02:16,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1239535_168_S_6827.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  48%|████▊     | 381/802 [01:58<02:19,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1237740_114_S_6813.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  48%|████▊     | 382/802 [01:58<02:27,  2.86it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I743631_130_S_5258.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  48%|████▊     | 383/802 [01:59<02:15,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I481644_041_S_5097.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  48%|████▊     | 384/802 [01:59<02:15,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1092329_116_S_6100.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  48%|████▊     | 385/802 [01:59<02:15,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1120772_116_S_6100.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  48%|████▊     | 386/802 [02:00<02:10,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1281547_116_S_6100.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  48%|████▊     | 387/802 [02:00<02:23,  2.90it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I944650_037_S_6144.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  48%|████▊     | 388/802 [02:00<02:18,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10237955_033_S_7079.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▊     | 389/802 [02:01<02:10,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1586128_033_S_7079.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▊     | 390/802 [02:01<02:24,  2.85it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1010814_002_S_4799.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▉     | 391/802 [02:01<02:33,  2.67it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I774043_002_S_4799.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  49%|████▉     | 392/802 [02:02<02:30,  2.72it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1165397_036_S_6179.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▉     | 393/802 [02:02<02:27,  2.77it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I958094_116_S_4453.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▉     | 394/802 [02:02<02:17,  2.96it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1280798_116_S_4453.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▉     | 395/802 [02:03<02:10,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1539913_116_S_4453.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  49%|████▉     | 396/802 [02:03<02:14,  3.01it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I974280_141_S_6240.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|████▉     | 397/802 [02:03<02:03,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1564284_033_S_6352.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|████▉     | 398/802 [02:04<02:05,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1174125_033_S_6352.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|████▉     | 399/802 [02:04<01:57,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1624603_033_S_6352.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|████▉     | 400/802 [02:04<01:51,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I996786_033_S_6352.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|█████     | 401/802 [02:04<01:59,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1018186_141_S_6416.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|█████     | 402/802 [02:05<01:57,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1511356_141_S_6416.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|█████     | 403/802 [02:05<02:05,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I387203_031_S_4149.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  50%|█████     | 404/802 [02:05<02:08,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1287192_024_S_6184.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  50%|█████     | 405/802 [02:06<02:10,  3.05it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I654975_041_S_4510.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  51%|█████     | 406/802 [02:06<02:05,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I824980_037_S_4410.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  51%|█████     | 407/802 [02:06<02:05,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1256853_141_S_6075.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  51%|█████     | 408/802 [02:07<02:00,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I911531_141_S_6075.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  51%|█████     | 409/802 [02:07<01:54,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I573502_135_S_4356.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  51%|█████     | 410/802 [02:07<01:58,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I957300_114_S_5234.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  51%|█████     | 411/802 [02:08<01:54,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1130063_114_S_5234.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  51%|█████▏    | 412/802 [02:08<01:58,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I983797_070_S_4856.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0000000000050022]

Processing T1 MRI DICOM folders:  51%|█████▏    | 413/802 [02:08<02:02,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1579645_070_S_4856.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 414/802 [02:09<02:00,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1252024_168_S_6051.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 415/802 [02:09<02:06,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I874879_168_S_6051.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 416/802 [02:09<02:00,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1009810_011_S_6418.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.9999999999960067]

Processing T1 MRI DICOM folders:  52%|█████▏    | 417/802 [02:09<01:57,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I901705_037_S_4030.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 418/802 [02:10<02:05,  3.05it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1052046_012_S_6503.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 419/802 [02:10<01:59,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1196891_032_S_0677.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 420/802 [02:10<02:04,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I879552_032_S_0677.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  52%|█████▏    | 421/802 [02:11<01:57,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1073428_109_S_6373.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 422/802 [02:11<01:57,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I931698_035_S_4785.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 423/802 [02:11<02:06,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I776218_100_S_0069.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  53%|█████▎    | 424/802 [02:12<02:07,  2.97it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1461224_070_S_6966.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 425/802 [02:12<01:59,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I958916_070_S_6191.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 426/802 [02:12<02:01,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I845577_141_S_0767.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 427/802 [02:13<01:54,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1152079_141_S_0767.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 428/802 [02:13<01:49,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1471354_141_S_0767.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  53%|█████▎    | 429/802 [02:13<01:59,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I554367_006_S_4960.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  54%|█████▎    | 430/802 [02:14<01:59,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I266848_099_S_2146.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  54%|█████▎    | 431/802 [02:14<01:52,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1039134_014_S_6437.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  54%|█████▍    | 432/802 [02:14<01:50,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1346790_014_S_6437.nii
Shape: (176, 256, 256), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  54%|█████▍    | 433/802 [02:14<01:51,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1040755_041_S_1418.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  54%|█████▍    | 434/802 [02:15<02:00,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I420366_100_S_4469.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  54%|█████▍    | 435/802 [02:15<01:53,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1628474_020_S_7098.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  54%|█████▍    | 436/802 [02:15<01:59,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1031685_168_S_6492.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  54%|█████▍    | 437/802 [02:16<01:51,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I957994_116_S_6119.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  55%|█████▍    | 438/802 [02:16<01:46,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1025881_032_S_4277.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  55%|█████▍    | 439/802 [02:16<01:51,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1225896_032_S_4277.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  55%|█████▍    | 440/802 [02:17<01:48,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I881980_032_S_4277.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  55%|█████▍    | 441/802 [02:17<01:53,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I705050_135_S_4722.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10333997_016_S_6941.nii
Shape: (128, 256, 240), Spacing: [1.0546875, 1.0546875, 1.2000000476837]

Processing T1 MRI DICOM folders:  55%|█████▌    | 443/802 [02:17<01:40,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I310898_099_S_4076.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  55%|█████▌    | 444/802 [02:18<01:50,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1256135_168_S_6059.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  55%|█████▌    | 445/802 [02:18<01:48,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892759_168_S_6059.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▌    | 446/802 [02:18<01:50,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1296519_116_S_4043.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▌    | 447/802 [02:19<01:45,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I969402_116_S_4043.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▌    | 448/802 [02:19<01:40,  3.52it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1609558_116_S_4043.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▌    | 449/802 [02:19<01:43,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1075339_013_S_4268.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▌    | 450/802 [02:20<01:43,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1177263_941_S_5193.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▌    | 451/802 [02:20<01:48,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I900932_037_S_0454.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  56%|█████▋    | 452/802 [02:20<01:56,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I574355_006_S_4357.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1327480_177_S_6409.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 454/802 [02:21<01:30,  3.83it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I839474_141_S_6008.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 455/802 [02:21<01:30,  3.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1170869_141_S_6008.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 456/802 [02:21<01:36,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1475753_141_S_6008.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 457/802 [02:22<01:35,  3.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1101652_141_S_6008.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 458/802 [02:22<01:37,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I902070_012_S_4094.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 459/802 [02:22<01:41,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1344400_116_S_6517.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 460/802 [02:22<01:37,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1047168_116_S_6517.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  57%|█████▋    | 461/802 [02:23<01:35,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I939884_114_S_6063.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  58%|█████▊    | 462/802 [02:23<01:37,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1400194_114_S_6063.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  58%|█████▊    | 463/802 [02:23<01:33,  3.61it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1009372_070_S_6394.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  58%|█████▊    | 464/802 [02:24<01:32,  3.66it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I980928_114_S_6251.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  58%|█████▊    | 466/802 [02:24<01:25,  3.91it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1226508_114_S_6251.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I24431_128_S_0200.nii
Shape: (160, 192, 192), Spacing: [1.25, 1.25, 1.2000000000000028]

Processing T1 MRI DICOM folders:  58%|█████▊    | 467/802 [02:24<01:34,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I862016_032_S_2119.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  58%|█████▊    | 468/802 [02:25<01:33,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1249336_003_S_4119.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  58%|█████▊    | 469/802 [02:25<01:32,  3.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1514449_003_S_4119.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▊    | 470/802 [02:25<01:36,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I703837_135_S_4723.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826650054]

Processing T1 MRI DICOM folders:  59%|█████▊    | 471/802 [02:26<01:35,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1235482_168_S_6467.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▉    | 472/802 [02:26<01:44,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1017238_168_S_6467.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▉    | 473/802 [02:26<01:37,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1189178_013_S_6768.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▉    | 474/802 [02:26<01:34,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1261558_116_S_6543.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▉    | 475/802 [02:27<01:37,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1038941_116_S_6543.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▉    | 476/802 [02:27<01:33,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1363593_128_S_4607.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  59%|█████▉    | 477/802 [02:27<01:41,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I944327_032_S_4429.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|█████▉    | 478/802 [02:28<01:38,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1042944_002_S_5230.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|█████▉    | 479/802 [02:28<01:34,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I884806_002_S_5230.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|█████▉    | 480/802 [02:28<01:39,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1119575_003_S_6678.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|█████▉    | 481/802 [02:28<01:32,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1387539_114_S_6462.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|██████    | 482/802 [02:29<01:29,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1060030_114_S_6462.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|██████    | 483/802 [02:29<01:31,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1697549_033_S_7066.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|██████    | 484/802 [02:29<01:28,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1570686_033_S_7066.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  60%|██████    | 485/802 [02:30<01:27,  3.63it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1226896_127_S_6241.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  61%|██████    | 486/802 [02:30<01:44,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I576769_130_S_0969.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  61%|██████    | 487/802 [02:30<01:37,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I944155_116_S_6129.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1092240_114_S_6039.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  61%|██████    | 489/802 [02:31<01:20,  3.87it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I879209_114_S_6039.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  61%|██████    | 490/802 [02:31<01:32,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I758055_053_S_4813.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  61%|██████    | 491/802 [02:31<01:31,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1633742_033_S_7114.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  61%|██████▏   | 492/802 [02:32<01:30,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1259913_068_S_2184.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  61%|██████▏   | 493/802 [02:32<01:30,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1618761_068_S_2184.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  62%|██████▏   | 494/802 [02:32<01:36,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I920082_068_S_2184.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  62%|██████▏   | 495/802 [02:33<01:30,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I336657_099_S_4157.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  62%|██████▏   | 496/802 [02:33<01:36,  3.16it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I334144_129_S_0778.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  62%|██████▏   | 497/802 [02:33<01:37,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1170118_011_S_6367.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  62%|██████▏   | 498/802 [02:34<01:32,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I998447_011_S_6367.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  62%|██████▏   | 499/802 [02:34<01:26,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I485046_041_S_5100.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  62%|██████▏   | 500/802 [02:34<01:27,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1142218_033_S_6697.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  62%|██████▏   | 501/802 [02:34<01:23,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I358679_128_S_2220.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826630017]

Processing T1 MRI DICOM folders:  63%|██████▎   | 502/802 [02:35<01:31,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I959742_035_S_4464.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 503/802 [02:35<01:27,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1152910_014_S_6145.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 504/802 [02:35<01:25,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1299912_014_S_6145.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 505/802 [02:36<01:29,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I948081_014_S_6145.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 506/802 [02:36<01:24,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1028011_109_S_6405.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 507/802 [02:36<01:29,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1038043_941_S_6068.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 508/802 [02:36<01:25,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1562938_141_S_6116.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  63%|██████▎   | 509/802 [02:37<01:27,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I935952_141_S_6116.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  64%|██████▎   | 510/802 [02:37<01:23,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1264670_141_S_6116.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  64%|██████▎   | 511/802 [02:37<01:20,  3.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1523003_141_S_6116.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  64%|██████▍   | 512/802 [02:38<01:23,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I644643_041_S_4427.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  64%|██████▍   | 513/802 [02:38<01:19,  3.63it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I525047_041_S_4271.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  64%|██████▍   | 514/802 [02:38<01:20,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1428762_168_S_6921.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  64%|██████▍   | 515/802 [02:38<01:28,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1622124_168_S_6921.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  64%|██████▍   | 516/802 [02:39<01:34,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I348300_129_S_4371.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  64%|██████▍   | 517/802 [02:39<01:24,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I667742_137_S_4520.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  65%|██████▍   | 518/802 [02:39<01:29,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1415399_036_S_4389.nii
Shape: (208, 256, 256), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▍   | 519/802 [02:40<01:31,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1385427_168_S_6541.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▍   | 520/802 [02:40<01:30,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1586427_168_S_6541.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▍   | 521/802 [02:40<01:33,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1237998_168_S_6541.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▌   | 522/802 [02:41<01:30,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1036163_168_S_6541.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▌   | 523/802 [02:41<01:35,  2.93it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I939835_068_S_0210.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▌   | 524/802 [02:41<01:34,  2.93it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I992613_168_S_6321.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  65%|██████▌   | 525/802 [02:42<01:31,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1603690_168_S_6321.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▌   | 526/802 [02:42<01:33,  2.94it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1351301_168_S_6321.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▌   | 527/802 [02:43<01:35,  2.89it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I990113_013_S_4580.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▌   | 528/802 [02:43<01:38,  2.79it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1485595_013_S_4580.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▌   | 529/802 [02:43<01:31,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1193762_032_S_6293.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▌   | 530/802 [02:43<01:24,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I993285_032_S_6293.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▌   | 531/802 [02:44<01:22,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I984807_033_S_6298.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▋   | 532/802 [02:44<01:16,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1165491_033_S_6298.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  66%|██████▋   | 533/802 [02:44<01:17,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1320212_033_S_6298.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  67%|██████▋   | 534/802 [02:45<01:16,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I879568_032_S_6055.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  67%|██████▋   | 535/802 [02:45<01:14,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I938767_002_S_6103.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  67%|██████▋   | 536/802 [02:45<01:20,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1117314_037_S_0377.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  67%|██████▋   | 537/802 [02:45<01:18,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1001975_002_S_4654.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  67%|██████▋   | 538/802 [02:46<01:23,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I687381_002_S_4654.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  67%|██████▋   | 539/802 [02:46<01:22,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I315822_099_S_4104.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  67%|██████▋   | 540/802 [02:46<01:18,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I992208_032_S_6294.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  67%|██████▋   | 541/802 [02:47<01:24,  3.09it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1067140_024_S_5290.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  68%|██████▊   | 542/802 [02:47<01:17,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I439516_041_S_4876.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  68%|██████▊   | 543/802 [02:47<01:24,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I502018_002_S_5178.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  68%|██████▊   | 544/802 [02:48<01:19,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I984486_116_S_4199.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  68%|██████▊   | 545/802 [02:48<01:15,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1325755_116_S_4199.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  68%|██████▊   | 546/802 [02:48<01:18,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1133016_116_S_4199.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  68%|██████▊   | 547/802 [02:49<01:16,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1043570_941_S_4365.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  68%|██████▊   | 548/802 [02:49<01:19,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I929106_011_S_4893.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  68%|██████▊   | 549/802 [02:49<01:14,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I925543_114_S_0416.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▊   | 550/802 [02:49<01:11,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1214021_114_S_0416.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▊   | 551/802 [02:50<01:14,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1360617_141_S_6779.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▉   | 552/802 [02:50<01:14,  3.36it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I953859_007_S_4272.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▉   | 553/802 [02:50<01:16,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1072748_141_S_6589.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▉   | 554/802 [02:51<01:17,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1222562_128_S_4742.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▉   | 555/802 [02:51<01:15,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1456305_003_S_6959.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▉   | 556/802 [02:51<01:21,  3.03it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I942907_007_S_4620.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  69%|██████▉   | 557/802 [02:52<01:17,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1320573_116_S_6439.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  70%|██████▉   | 558/802 [02:52<01:19,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1015823_116_S_6439.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  70%|██████▉   | 560/802 [02:52<01:03,  3.81it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1209877_941_S_6058.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I655394_018_S_2180.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  70%|███████   | 562/802 [02:53<01:01,  3.88it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1555330_041_S_0679.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I503081_041_S_0679.nii
Shape: (160, 192, 192), Spacing: [1.25, 1.25, 1.2000000000000028]

Processing T1 MRI DICOM folders:  70%|███████   | 563/802 [02:53<01:01,  3.90it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1011824_114_S_6347.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  70%|███████   | 564/802 [02:54<01:07,  3.52it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1230907_032_S_6804.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  70%|███████   | 565/802 [02:54<01:08,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892735_068_S_4424.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████   | 566/802 [02:54<01:08,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1495816_003_S_7010.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████   | 567/802 [02:55<01:14,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I987768_168_S_6318.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████   | 568/802 [02:55<01:14,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1603670_168_S_6320.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████   | 569/802 [02:55<01:18,  2.97it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I992584_168_S_6320.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████   | 570/802 [02:56<01:16,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1349784_168_S_6320.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████   | 571/802 [02:56<01:11,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I259770_057_S_2398.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  71%|███████▏  | 572/802 [02:56<01:14,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1058589_032_S_6602.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  71%|███████▏  | 573/802 [02:56<01:11,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1253903_032_S_6602.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  72%|███████▏  | 574/802 [02:57<01:15,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1048360_052_S_1352.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  72%|███████▏  | 575/802 [02:57<01:20,  2.81it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1153521_130_S_4417.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  72%|███████▏  | 576/802 [02:58<01:16,  2.97it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1555916_011_S_7028.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  72%|███████▏  | 577/802 [02:58<01:15,  2.98it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1173479_022_S_2379.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0000000000050022]

Processing T1 MRI DICOM folders:  72%|███████▏  | 578/802 [02:58<01:11,  3.15it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I848161_022_S_2379.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  72%|███████▏  | 579/802 [02:58<01:07,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I985197_011_S_6303.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  72%|███████▏  | 580/802 [02:59<01:12,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1160021_011_S_6303.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  72%|███████▏  | 581/802 [02:59<01:09,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1071185_014_S_2308.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 582/802 [02:59<01:12,  3.02it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I899456_014_S_2308.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 583/802 [03:00<01:08,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1195514_014_S_2308.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 584/802 [03:00<01:04,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1403921_014_S_2308.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 585/802 [03:00<01:05,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1610001_014_S_2308.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 586/802 [03:01<01:00,  3.56it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1070545_033_S_5259.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 587/802 [03:01<00:56,  3.79it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1250808_033_S_5259.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 588/802 [03:01<00:59,  3.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I942819_033_S_5259.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  73%|███████▎  | 589/802 [03:01<01:01,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1406556_168_S_6902.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  74%|███████▎  | 590/802 [03:02<01:08,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I915041_035_S_4414.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  74%|███████▎  | 591/802 [03:02<01:06,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1274614_168_S_6591.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  74%|███████▍  | 592/802 [03:02<01:07,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1054570_168_S_6591.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  74%|███████▍  | 593/802 [03:03<01:10,  2.95it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1378374_168_S_6591.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  74%|███████▍  | 594/802 [03:03<01:14,  2.79it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I460914_018_S_2133.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  74%|███████▍  | 595/802 [03:04<01:16,  2.70it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I395111_002_S_4225.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  74%|███████▍  | 596/802 [03:04<01:09,  2.95it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1303187_070_S_6236.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  74%|███████▍  | 597/802 [03:04<01:06,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1431746_070_S_6236.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  75%|███████▍  | 598/802 [03:04<01:08,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1140075_070_S_6236.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  75%|███████▍  | 599/802 [03:05<01:04,  3.17it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1574894_070_S_6236.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  75%|███████▍  | 600/802 [03:05<01:01,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I968277_070_S_6236.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  75%|███████▍  | 601/802 [03:05<01:04,  3.12it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1117300_037_S_0150.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  75%|███████▌  | 602/802 [03:06<01:08,  2.94it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I651399_002_S_4473.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  75%|███████▌  | 603/802 [03:06<01:02,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I893570_041_S_5141.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.199999982662007]

Processing T1 MRI DICOM folders:  75%|███████▌  | 604/802 [03:06<01:04,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I959645_041_S_6192.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  75%|███████▌  | 605/802 [03:07<01:00,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I972974_109_S_6215.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▌  | 606/802 [03:07<01:00,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1042535_068_S_0802.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▌  | 607/802 [03:07<01:05,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I878974_068_S_0802.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▌  | 608/802 [03:08<01:01,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I992776_114_S_6309.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▌  | 609/802 [03:08<01:03,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I863251_003_S_4644.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▌  | 610/802 [03:08<00:59,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1477561_003_S_4644.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▌  | 611/802 [03:09<00:58,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1178908_003_S_4644.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  76%|███████▋  | 612/802 [03:09<00:58,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1219559_041_S_4051.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  76%|███████▋  | 613/802 [03:09<00:54,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I872883_041_S_4051.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.199999982659989]

Processing T1 MRI DICOM folders:  77%|███████▋  | 614/802 [03:09<00:58,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I930626_168_S_6108.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  77%|███████▋  | 615/802 [03:10<00:55,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I888008_002_S_4213.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  77%|███████▋  | 616/802 [03:10<00:53,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I898881_011_S_4827.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  77%|███████▋  | 617/802 [03:10<00:57,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1175356_168_S_6735.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  77%|███████▋  | 618/802 [03:11<00:55,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1021826_020_S_6470.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  77%|███████▋  | 619/802 [03:11<00:53,  3.41it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I894404_037_S_4308.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 0.9999999999960067]

Processing T1 MRI DICOM folders:  77%|███████▋  | 620/802 [03:11<00:54,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1037417_014_S_6502.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  77%|███████▋  | 621/802 [03:12<00:53,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I861838_037_S_6032.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  78%|███████▊  | 622/802 [03:12<00:55,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I949873_114_S_4404.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  78%|███████▊  | 623/802 [03:12<00:52,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1142242_114_S_4404.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1257600_114_S_4404.nii
Shape: (160, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  78%|███████▊  | 625/802 [03:13<00:50,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I995496_002_S_1155.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  78%|███████▊  | 626/802 [03:13<00:49,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1510290_141_S_7013.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  78%|███████▊  | 627/802 [03:13<00:46,  3.77it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I339165_128_S_2036.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826610122]

Processing T1 MRI DICOM folders:  78%|███████▊  | 628/802 [03:13<00:47,  3.65it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1235084_033_S_6824.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  78%|███████▊  | 629/802 [03:14<00:48,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1252687_941_S_6080.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  79%|███████▊  | 630/802 [03:14<00:51,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1090114_003_S_2374.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  79%|███████▊  | 631/802 [03:14<00:48,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I969812_109_S_6213.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  79%|███████▉  | 632/802 [03:15<00:45,  3.70it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I941811_033_S_1098.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  79%|███████▉  | 633/802 [03:15<00:48,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I622501_130_S_4405.nii
Shape: (140, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  79%|███████▉  | 634/802 [03:15<00:53,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1018478_013_S_6206.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  79%|███████▉  | 635/802 [03:16<00:50,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1471775_013_S_6206.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  79%|███████▉  | 636/802 [03:16<00:47,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I530870_135_S_4281.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982660998]

Processing T1 MRI DICOM folders:  79%|███████▉  | 637/802 [03:16<00:48,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1117449_036_S_4538.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  80%|███████▉  | 639/802 [03:17<00:45,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I350736_129_S_4396.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10313743_016_S_6816.nii
Shape: (120, 256, 240), Spacing: [1.0546875, 1.0546875, 1.2000000476837]

Processing T1 MRI DICOM folders:  80%|███████▉  | 640/802 [03:17<00:45,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I914845_037_S_4706.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  80%|███████▉  | 641/802 [03:17<00:48,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1078739_114_S_6595.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  80%|████████  | 642/802 [03:18<00:47,  3.36it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I951181_168_S_6131.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  80%|████████  | 643/802 [03:18<00:50,  3.15it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I769530_053_S_2396.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  80%|████████  | 644/802 [03:18<00:48,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1154566_003_S_4441.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  80%|████████  | 645/802 [03:19<00:48,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1430377_003_S_4441.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████  | 646/802 [03:19<00:45,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1466184_141_S_6964.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████  | 647/802 [03:19<00:47,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1184033_014_S_6765.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████  | 648/802 [03:19<00:45,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1351663_014_S_6765.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████  | 649/802 [03:20<00:43,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1609974_014_S_6765.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████  | 650/802 [03:20<00:46,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I930689_168_S_6107.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████  | 651/802 [03:20<00:42,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I631880_009_S_4324.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.199999982659989]

Processing T1 MRI DICOM folders:  81%|████████▏ | 652/802 [03:21<00:41,  3.64it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1619004_033_S_7100.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  81%|████████▏ | 653/802 [03:21<00:44,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I913456_068_S_4431.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  82%|████████▏ | 654/802 [03:21<00:43,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1118918_068_S_4431.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  82%|████████▏ | 655/802 [03:22<00:44,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1607792_003_S_4872.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  82%|████████▏ | 656/802 [03:22<00:42,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I561330_082_S_5282.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  82%|████████▏ | 657/802 [03:22<00:40,  3.61it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I634519_135_S_4446.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  82%|████████▏ | 658/802 [03:22<00:41,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1576345_041_S_4200.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  82%|████████▏ | 659/802 [03:23<00:39,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I522559_041_S_4200.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  82%|████████▏ | 660/802 [03:23<00:43,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I914999_003_S_4288.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  82%|████████▏ | 661/802 [03:23<00:41,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1226294_003_S_4288.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  83%|████████▎ | 662/802 [03:24<00:41,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I894263_007_S_2394.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  83%|████████▎ | 663/802 [03:24<00:41,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I679922_941_S_4187.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  83%|████████▎ | 664/802 [03:24<00:38,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I262420_098_S_2079.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  83%|████████▎ | 665/802 [03:24<00:40,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1018201_020_S_6449.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  83%|████████▎ | 666/802 [03:25<00:38,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1325857_020_S_6449.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  83%|████████▎ | 667/802 [03:25<00:38,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1491890_941_S_6044.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  83%|████████▎ | 668/802 [03:25<00:40,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I974943_032_S_6211.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  83%|████████▎ | 669/802 [03:26<00:38,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1174901_032_S_6211.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▎ | 670/802 [03:26<00:40,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1616503_168_S_6350.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▎ | 671/802 [03:26<00:39,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1381875_168_S_6350.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▍ | 672/802 [03:26<00:38,  3.38it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I997533_168_S_6350.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▍ | 673/802 [03:27<00:39,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I992757_070_S_5040.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▍ | 674/802 [03:27<00:41,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I531785_019_S_4293.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  84%|████████▍ | 675/802 [03:27<00:38,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1332407_020_S_6227.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▍ | 676/802 [03:28<00:39,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I966268_020_S_6227.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  84%|████████▍ | 677/802 [03:28<00:36,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1154753_032_S_6700.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▍ | 678/802 [03:28<00:35,  3.49it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1274808_020_S_5140.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▍ | 679/802 [03:29<00:36,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I935824_020_S_5140.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▍ | 680/802 [03:29<00:35,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I833978_037_S_4071.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▍ | 681/802 [03:29<00:36,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1032531_116_S_6550.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▌ | 682/802 [03:29<00:34,  3.51it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1485046_116_S_6550.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▌ | 683/802 [03:30<00:32,  3.64it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1215082_116_S_6550.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▌ | 684/802 [03:30<00:34,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1331166_116_S_6550.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  85%|████████▌ | 685/802 [03:30<00:32,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I988538_002_S_6007.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▌ | 686/802 [03:31<00:31,  3.71it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I360516_099_S_4463.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  86%|████████▌ | 687/802 [03:31<00:32,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1578065_070_S_6911.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▌ | 688/802 [03:31<00:31,  3.65it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1417067_070_S_6911.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▌ | 689/802 [03:31<00:31,  3.63it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1027631_020_S_6504.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▌ | 690/802 [03:32<00:32,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1349118_020_S_6504.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▌ | 691/802 [03:32<00:30,  3.67it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1598296_033_S_7088.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▋ | 692/802 [03:32<00:30,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10246655_033_S_7088.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  86%|████████▋ | 693/802 [03:33<00:31,  3.46it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I922723_035_S_0156.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 694/802 [03:33<00:30,  3.56it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1281566_116_S_6133.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 695/802 [03:33<00:31,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I945601_116_S_6133.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 696/802 [03:33<00:29,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1122101_116_S_6133.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 697/802 [03:34<00:30,  3.43it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1167388_002_S_6009.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 698/802 [03:34<00:29,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I983052_022_S_6280.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 699/802 [03:34<00:27,  3.72it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1334455_033_S_6705.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 700/802 [03:34<00:28,  3.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1440205_033_S_6705.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  87%|████████▋ | 701/802 [03:35<00:26,  3.82it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1147596_033_S_6705.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 702/802 [03:35<00:29,  3.42it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I952046_037_S_6141.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 703/802 [03:35<00:28,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I871844_141_S_6041.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 704/802 [03:36<00:27,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1513708_003_S_4900.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 705/802 [03:36<00:29,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1255144_003_S_4900.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 706/802 [03:36<00:27,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1639219_011_S_7112.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 707/802 [03:37<00:29,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1153585_130_S_4343.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  88%|████████▊ | 708/802 [03:37<00:30,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1082571_003_S_0908.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  88%|████████▊ | 709/802 [03:37<00:28,  3.27it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I969412_003_S_0908.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  89%|████████▊ | 710/802 [03:37<00:27,  3.34it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1249274_003_S_0908.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  89%|████████▊ | 711/802 [03:38<00:25,  3.58it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I502287_003_S_0908.nii
Shape: (160, 192, 192), Spacing: [1.25, 1.25, 1.2000000000000028]

Processing T1 MRI DICOM folders:  89%|████████▉ | 712/802 [03:38<00:24,  3.62it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1152416_032_S_6709.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  89%|████████▉ | 713/802 [03:38<00:27,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I583247_053_S_5296.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  89%|████████▉ | 714/802 [03:39<00:26,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1683063_041_S_5253.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  89%|████████▉ | 715/802 [03:39<00:24,  3.53it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I502402_041_S_5253.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  89%|████████▉ | 716/802 [03:39<00:27,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I917090_168_S_6086.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  89%|████████▉ | 717/802 [03:40<00:25,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I511775_123_S_4127.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  90%|████████▉ | 718/802 [03:40<00:24,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I940645_037_S_6115.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  90%|████████▉ | 719/802 [03:40<00:24,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I851352_141_S_6015.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  90%|████████▉ | 720/802 [03:40<00:23,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1170887_141_S_6015.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  90%|████████▉ | 721/802 [03:41<00:22,  3.63it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1472512_141_S_6015.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  90%|█████████ | 722/802 [03:41<00:23,  3.36it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1412023_020_S_6901.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  90%|█████████ | 723/802 [03:41<00:23,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1557901_020_S_6901.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  90%|█████████ | 724/802 [03:42<00:24,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I379341_031_S_2018.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  90%|█████████ | 725/802 [03:42<00:23,  3.32it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1190913_003_S_6432.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████ | 726/802 [03:42<00:24,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1016012_003_S_6432.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████ | 727/802 [03:43<00:23,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1045619_020_S_6566.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████ | 728/802 [03:43<00:24,  3.06it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1005735_003_S_6264.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████ | 729/802 [03:43<00:22,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I549849_135_S_4309.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  91%|█████████ | 730/802 [03:43<00:21,  3.30it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I986205_168_S_6285.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████ | 731/802 [03:44<00:22,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I878146_002_S_6053.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████▏| 732/802 [03:44<00:21,  3.31it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1460759_003_S_4354.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  91%|█████████▏| 733/802 [03:44<00:21,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I863643_003_S_4354.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 734/802 [03:45<00:20,  3.25it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1091953_003_S_4354.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 735/802 [03:45<00:21,  3.07it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1181460_003_S_4354.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 736/802 [03:45<00:20,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1235535_003_S_6067.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 737/802 [03:46<00:21,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I912447_003_S_6067.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 738/802 [03:46<00:20,  3.19it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1511194_003_S_6067.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 739/802 [03:46<00:18,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1302699_022_S_5004.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 740/802 [03:47<00:17,  3.48it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1428959_022_S_5004.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  92%|█████████▏| 741/802 [03:47<00:17,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1152869_022_S_5004.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  93%|█████████▎| 742/802 [03:47<00:16,  3.64it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I973603_022_S_5004.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  93%|█████████▎| 743/802 [03:47<00:16,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1446679_070_S_6942.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  93%|█████████▎| 744/802 [03:48<00:16,  3.59it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I343458_099_S_4205.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  93%|█████████▎| 745/802 [03:48<00:17,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1229529_002_S_6030.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  93%|█████████▎| 746/802 [03:48<00:18,  3.11it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I343372_129_S_4287.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  93%|█████████▎| 747/802 [03:49<00:16,  3.40it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1607547_033_S_6969.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  93%|█████████▎| 748/802 [03:49<00:14,  3.61it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1457246_033_S_6969.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  93%|█████████▎| 749/802 [03:49<00:14,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10245496_033_S_6969.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▎| 750/802 [03:49<00:14,  3.63it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1018387_141_S_6423.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▎| 751/802 [03:50<00:13,  3.68it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1226456_014_S_4576.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▍| 752/802 [03:50<00:14,  3.44it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1072377_014_S_4576.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▍| 753/802 [03:50<00:13,  3.54it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I899473_014_S_4576.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▍| 754/802 [03:50<00:13,  3.56it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1555583_014_S_4576.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▍| 755/802 [03:51<00:13,  3.39it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I361240_099_S_4498.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  94%|█████████▍| 756/802 [03:51<00:12,  3.57it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1221673_013_S_6780.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  94%|█████████▍| 757/802 [03:51<00:13,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I353802_129_S_4422.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1340855_177_S_6448.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  95%|█████████▍| 759/802 [03:52<00:11,  3.90it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I915134_041_S_4974.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  95%|█████████▍| 760/802 [03:52<00:11,  3.79it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1075497_941_S_4036.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  95%|█████████▍| 761/802 [03:52<00:11,  3.69it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1233189_168_S_6815.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  95%|█████████▌| 762/802 [03:53<00:11,  3.50it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I915862_011_S_4105.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  95%|█████████▌| 763/802 [03:53<00:10,  3.60it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1032324_070_S_6548.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  95%|█████████▌| 764/802 [03:53<00:11,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I969431_014_S_6210.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  95%|█████████▌| 765/802 [03:54<00:10,  3.55it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I641043_041_S_4513.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  96%|█████████▌| 766/802 [03:54<00:10,  3.47it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I908698_068_S_0127.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▌| 767/802 [03:54<00:10,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1070417_068_S_0127.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▌| 768/802 [03:55<00:10,  3.15it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1378326_068_S_0127.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▌| 769/802 [03:55<00:11,  3.00it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1303143_068_S_0127.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▌| 770/802 [03:55<00:10,  3.04it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1349605_036_S_6189.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▌| 771/802 [03:56<00:10,  2.97it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1154769_032_S_6701.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▋| 772/802 [03:56<00:09,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1324187_141_S_6872.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  96%|█████████▋| 773/802 [03:56<00:09,  2.97it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1293047_052_S_2249.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  97%|█████████▋| 774/802 [03:57<00:08,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10231043_070_S_6386.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  97%|█████████▋| 775/802 [03:57<00:09,  2.98it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1006805_070_S_6386.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  97%|█████████▋| 776/802 [03:57<00:09,  2.87it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I940663_037_S_6125.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  97%|█████████▋| 777/802 [03:58<00:08,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I944379_003_S_6092.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]
Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I266063_057_S_0934.nii
Shape: (160, 192, 192), Spacing: [1.25, 1.25, 1.1999999999999886]

Processing T1 MRI DICOM folders:  97%|█████████▋| 779/802 [03:58<00:07,  3.23it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I907712_014_S_6076.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  97%|█████████▋| 780/802 [03:58<00:06,  3.37it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1072841_014_S_6076.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  97%|█████████▋| 781/802 [03:59<00:06,  3.29it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1254369_014_S_6076.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 782/802 [03:59<00:05,  3.45it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1558652_014_S_6076.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 783/802 [03:59<00:06,  3.15it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1015398_168_S_6426.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 784/802 [04:00<00:06,  2.99it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1241416_168_S_6426.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 785/802 [04:00<00:05,  3.13it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I942682_013_S_2389.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 786/802 [04:00<00:04,  3.21it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1037394_014_S_6424.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 787/802 [04:01<00:04,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1491025_014_S_6424.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  98%|█████████▊| 788/802 [04:01<00:04,  2.94it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I336183_129_S_4220.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders:  98%|█████████▊| 789/802 [04:01<00:04,  3.18it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1529331_013_S_6975.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  99%|█████████▊| 790/802 [04:02<00:03,  3.08it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I763574_941_S_4292.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826600032]

Processing T1 MRI DICOM folders:  99%|█████████▊| 791/802 [04:02<00:03,  3.22it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I844181_022_S_6013.nii
Shape: (176, 256, 240), Spacing: [1.0546875, 1.0546875, 1.1999999826600032]

Processing T1 MRI DICOM folders:  99%|█████████▉| 792/802 [04:02<00:02,  3.35it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1184047_022_S_6013.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  99%|█████████▉| 793/802 [04:03<00:02,  3.15it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1250826_068_S_4340.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  99%|█████████▉| 794/802 [04:03<00:02,  3.20it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I892747_068_S_4340.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  99%|█████████▉| 795/802 [04:03<00:02,  2.98it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I10238706_068_S_4340.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders:  99%|█████████▉| 796/802 [04:03<00:01,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I656646_137_S_4482.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.1999999826699934]

Processing T1 MRI DICOM folders:  99%|█████████▉| 797/802 [04:04<00:01,  3.10it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I659919_053_S_4578.nii
Shape: (170, 256, 256), Spacing: [1.0, 1.0, 1.2]

Processing T1 MRI DICOM folders: 100%|█████████▉| 798/802 [04:04<00:01,  3.24it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1273702_003_S_6606.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders: 100%|█████████▉| 799/802 [04:04<00:00,  3.14it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1071822_003_S_6606.nii
Shape: (208, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders: 100%|█████████▉| 800/802 [04:05<00:00,  3.33it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1123765_116_S_4855.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders: 100%|█████████▉| 801/802 [04:05<00:00,  3.28it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1544995_116_S_4855.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

Processing T1 MRI DICOM folders: 100%|██████████| 802/802 [04:05<00:00,  3.26it/s]

Saved T1 MRI to model_data/adni/t1_long_data/t1_long_raw/I1304066_116_S_4855.nii
Shape: (176, 256, 240), Spacing: [1.0, 1.0, 1.0]

T1 MRI Processing complete!
Successfully processed: 802
Errors: 0

In [7]:
# Example usage for your ADNI data structure:
# For a single subject's ADC map:
adc_map, affine = dicom_to_adc_map(
    "model_data/adni/dti_dcm/002_S_1280/Axial_DTI_ADC/2017-03-13_14_12_25.0/I829303",
    output_path="model_data/adni/dti_raw/I829303_002_S_1280_ADC.nii"
)

Saved ADC map to model_data/adni/dti_raw/I829303_002_S_1280_ADC.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]

In [8]:
# Process all I* folders in dti_dcm and save to dti_raw
base_dir = Path("model_data/adni/dti_dcm")
output_dir = Path("model_data/adni/dti_raw")
output_dir.mkdir(parents=True, exist_ok=True)

# Find all folders matching pattern I* (starting with I followed by digits)
processed = 0
errors = 0

In [8]:
# Collect all I* folders that contain DICOM files
i_folders = [f for f in base_dir.rglob("I*") 
             if f.is_dir() and (any(f.glob("*.dcm")) or any(f.glob("*.DCM")))]

In [12]:
# Process each folder with progress bar
for i_folder in tqdm(i_folders, desc="Processing DICOM folders"):
    try:
        # Extract image_id (the I* folder name, e.g., I829303)
        image_id = i_folder.name
        
        # Extract subject_id from the relative path
        # The structure is: dti_dcm/[subject_id]/.../I[image_id]
        relative_path = i_folder.relative_to(base_dir)
        subject_id = relative_path.parts[0]  # First part is the subject_id
        
        # Create output filename: I[image_id]_[subject_id].nii
        output_filename = f"{image_id}_{subject_id}.nii"
        output_path = output_dir / output_filename
        
        # Skip if already exists
        if output_path.exists():
            continue
        
        # Convert DICOM to ADC map
        adc_map, affine = dicom_to_adc_map(i_folder, output_path)
        processed += 1
        
    except Exception as e:
        print(f"\nError processing {i_folder}: {e}")
        errors += 1
        continue

print(f"\nProcessing complete!")
print(f"Successfully processed: {processed}")
print(f"Errors: {errors}")

Processing DICOM folders:   1%|          | 2/299 [00:00<00:25, 11.54it/s]

Saved ADC map to model_data/adni/dti_raw/I1593306_023_S_6400.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1193759_016_S_6789.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:   1%|▏         | 4/299 [00:00<00:22, 12.89it/s]

Saved ADC map to model_data/adni/dti_raw/I1116506_137_S_4631.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1282878_137_S_4631.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1417012_137_S_4631.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:   3%|▎         | 8/299 [00:00<00:21, 13.58it/s]

Saved ADC map to model_data/adni/dti_raw/I1274401_022_S_2263.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1194388_016_S_6773.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1498333_016_S_6773.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I351116_073_S_4777.nii
Shape: (3, 640, 640), Spacing: [1.71875, 1.71875, 5.2000001271566]

Processing DICOM folders:   4%|▎         | 11/299 [00:00<00:21, 13.50it/s]

Saved ADC map to model_data/adni/dti_raw/I1608082_016_S_6926.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1429651_016_S_6926.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:   4%|▍         | 13/299 [00:00<00:21, 13.31it/s]

Saved ADC map to model_data/adni/dti_raw/I923604_137_S_4299.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1130802_137_S_4299.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I929734_036_S_4430.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:   6%|▌         | 17/299 [00:01<00:19, 14.19it/s]

Saved ADC map to model_data/adni/dti_raw/I1445753_016_S_6943.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1581802_114_S_6057.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1415453_114_S_6057.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I942818_137_S_4466.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:   7%|▋         | 21/299 [00:01<00:22, 12.60it/s]

Saved ADC map to model_data/adni/dti_raw/I1359922_016_S_6381.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1000702_016_S_6381.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1493846_016_S_7002.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:   8%|▊         | 23/299 [00:01<00:21, 12.91it/s]

Saved ADC map to model_data/adni/dti_raw/I1546261_012_S_6760.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1180768_012_S_6760.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1346112_012_S_6760.nii
Shape: (80, 116, 116), Spacing: [2.6896550655365, 2.6896550655365, 2.0]

Processing DICOM folders:   8%|▊         | 25/299 [00:01<00:21, 12.96it/s]

Saved ADC map to model_data/adni/dti_raw/I882561_041_S_5078.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1194321_041_S_5078.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1056770_137_S_4862.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  10%|▉         | 29/299 [00:02<00:21, 12.53it/s]

Saved ADC map to model_data/adni/dti_raw/I1225180_137_S_4862.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1349940_137_S_4862.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1528898_023_S_4164.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1546919_036_S_7044.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  11%|█         | 32/299 [00:02<00:18, 14.40it/s]

Saved ADC map to model_data/adni/dti_raw/I1227915_041_S_6801.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1373556_041_S_6801.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  12%|█▏        | 36/299 [00:02<00:20, 12.88it/s]

Saved ADC map to model_data/adni/dti_raw/I1454387_137_S_6906.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1043642_137_S_6557.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I831081_002_S_1261.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  13%|█▎        | 38/299 [00:02<00:19, 13.06it/s]

Saved ADC map to model_data/adni/dti_raw/I984354_036_S_4491.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1507370_036_S_6885.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1263265_016_S_6839.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  13%|█▎        | 40/299 [00:03<00:19, 13.36it/s]

Saved ADC map to model_data/adni/dti_raw/I1584528_016_S_6839.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1426626_016_S_6839.nii
Shape: (15, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I916506_036_S_6088.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  15%|█▌        | 45/299 [00:03<00:19, 13.26it/s]

Saved ADC map to model_data/adni/dti_raw/I1360098_137_S_6880.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I916819_094_S_2201.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1494643_036_S_6878.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  16%|█▌        | 47/299 [00:03<00:18, 13.40it/s]

Saved ADC map to model_data/adni/dti_raw/I1576371_041_S_6786.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1219684_041_S_6786.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1359847_041_S_6786.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  16%|█▋        | 49/299 [00:03<00:18, 13.31it/s]

Saved ADC map to model_data/adni/dti_raw/I880650_941_S_6054.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1236026_016_S_6809.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  18%|█▊        | 53/299 [00:04<00:20, 12.12it/s]

Saved ADC map to model_data/adni/dti_raw/I1259792_016_S_6836.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1576316_041_S_4874.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1213049_041_S_4874.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  18%|█▊        | 55/299 [00:04<00:19, 12.31it/s]

Saved ADC map to model_data/adni/dti_raw/I884460_041_S_4874.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1046075_041_S_4874.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I958178_094_S_2238.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  19%|█▉        | 57/299 [00:04<00:19, 12.59it/s]

Saved ADC map to model_data/adni/dti_raw/I1138882_094_S_2238.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  20%|█▉        | 59/299 [00:04<00:23, 10.07it/s]

Saved ADC map to model_data/adni/dti_raw/I11151628_094_S_2238.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I916597_036_S_4715.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1438742_114_S_6917.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]

Processing DICOM folders:  21%|██▏       | 64/299 [00:05<00:17, 13.17it/s]

Saved ADC map to model_data/adni/dti_raw/I923862_941_S_4100.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1024406_094_S_6468.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1589918_023_S_6346.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1572547_114_S_6113.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]

Processing DICOM folders:  22%|██▏       | 66/299 [00:05<00:19, 11.74it/s]

Saved ADC map to model_data/adni/dti_raw/I1335380_114_S_6113.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1223391_016_S_6800.nii
Shape: (84, 116, 116), Spacing: [2.1034483909607, 2.1034483909607, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1426472_016_S_6800.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  23%|██▎       | 70/299 [00:05<00:18, 12.31it/s]

Saved ADC map to model_data/adni/dti_raw/I876892_941_S_6052.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I820332_016_S_4952.nii
Shape: (81, 104, 104), Spacing: [2.7115385532379, 2.7115385532379, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1172877_016_S_4952.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  24%|██▍       | 72/299 [00:05<00:20, 11.18it/s]

Saved ADC map to model_data/adni/dti_raw/I1285289_016_S_6853.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1223070_012_S_4188.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  25%|██▍       | 74/299 [00:05<00:18, 12.09it/s]

Saved ADC map to model_data/adni/dti_raw/I1387552_114_S_6524.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1653106_114_S_6524.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1242441_137_S_6826.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  26%|██▌       | 78/299 [00:06<00:18, 12.16it/s]

Saved ADC map to model_data/adni/dti_raw/I1404926_012_S_6073.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1239426_012_S_6073.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1013534_094_S_6417.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]

Processing DICOM folders:  27%|██▋       | 80/299 [00:06<00:20, 10.89it/s]

Saved ADC map to model_data/adni/dti_raw/I828706_024_S_6005.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I828702_024_S_6005.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  27%|██▋       | 82/299 [00:06<00:18, 11.43it/s]

Saved ADC map to model_data/adni/dti_raw/I873885_041_S_4037.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I944429_041_S_6136.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1267905_041_S_6136.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  29%|██▉       | 86/299 [00:06<00:17, 11.97it/s]

Saved ADC map to model_data/adni/dti_raw/I1017364_024_S_6033.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I946341_024_S_6033.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1059037_036_S_6466.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  29%|██▉       | 88/299 [00:07<00:19, 10.78it/s]

Saved ADC map to model_data/adni/dti_raw/I1213954_137_S_6693.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1417031_137_S_6693.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  30%|███       | 90/299 [00:07<00:18, 11.57it/s]

Saved ADC map to model_data/adni/dti_raw/I1508160_041_S_7017.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I863063_002_S_0413.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1014531_094_S_6419.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  32%|███▏      | 95/299 [00:07<00:14, 13.95it/s]

Saved ADC map to model_data/adni/dti_raw/I1326366_137_S_4351.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I925112_137_S_4351.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1620675_023_S_6535.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1548324_036_S_6897.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1591072_023_S_6399.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]

Processing DICOM folders:  33%|███▎      | 99/299 [00:07<00:14, 13.88it/s]

Saved ADC map to model_data/adni/dti_raw/I1335368_114_S_6597.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1534909_114_S_6597.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1370479_137_S_4536.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1257073_137_S_4536.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  34%|███▍      | 101/299 [00:08<00:14, 13.84it/s]

Saved ADC map to model_data/adni/dti_raw/I925992_137_S_4536.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1070900_137_S_4536.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  35%|███▌      | 105/299 [00:08<00:21,  9.23it/s]

Saved ADC map to model_data/adni/dti_raw/I1399028_114_S_2392.nii
Shape: (30, 1152, 1152), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1475452_114_S_2392.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1120048_137_S_6659.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  36%|███▌      | 107/299 [00:08<00:21,  9.14it/s]

Saved ADC map to model_data/adni/dti_raw/I973672_036_S_6231.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I975794_024_S_2239.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1002464_094_S_6278.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1538710_023_S_4115.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]

Processing DICOM folders:  37%|███▋      | 112/299 [00:09<00:16, 11.66it/s]

Saved ADC map to model_data/adni/dti_raw/I885682_024_S_4084.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1499634_016_S_6934.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1499645_016_S_6934.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  38%|███▊      | 114/299 [00:09<00:17, 10.58it/s]

Saved ADC map to model_data/adni/dti_raw/I1023442_036_S_2380.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I879765_041_S_4143.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  39%|███▉      | 116/299 [00:09<00:16, 11.34it/s]

Saved ADC map to model_data/adni/dti_raw/I1020344_041_S_4143.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1225009_012_S_4643.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1166768_012_S_4643.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  40%|████      | 120/299 [00:09<00:14, 12.00it/s]

Saved ADC map to model_data/adni/dti_raw/I1572641_036_S_6916.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I829303_002_S_1280.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I829314_002_S_1280.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  41%|████▏     | 124/299 [00:10<00:14, 11.99it/s]

Saved ADC map to model_data/adni/dti_raw/I829310_002_S_1280.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1391579_114_S_6429.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1667465_114_S_6429.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1079912_024_S_4674.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  42%|████▏     | 126/299 [00:10<00:14, 11.98it/s]

Saved ADC map to model_data/adni/dti_raw/I880436_024_S_4674.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I991870_036_S_6316.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1544046_036_S_6316.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  43%|████▎     | 128/299 [00:10<00:13, 12.74it/s]

Saved ADC map to model_data/adni/dti_raw/I1412989_016_S_6904.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1387177_114_S_6487.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]

Processing DICOM folders:  44%|████▍     | 132/299 [00:10<00:14, 11.77it/s]

Saved ADC map to model_data/adni/dti_raw/I1195550_041_S_5097.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I971722_041_S_5097.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1287827_041_S_5097.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  45%|████▍     | 134/299 [00:11<00:13, 12.06it/s]

Saved ADC map to model_data/adni/dti_raw/I854593_002_S_4799.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I957116_036_S_6179.nii
Shape: (81, 116, 116), Spacing: [2.1724138259888, 2.1724138259888, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1570945_036_S_7067.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  45%|████▌     | 136/299 [00:11<00:13, 12.26it/s]

Saved ADC map to model_data/adni/dti_raw/I958735_024_S_6184.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I914186_041_S_4510.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  47%|████▋     | 140/299 [00:11<00:13, 11.62it/s]

Saved ADC map to model_data/adni/dti_raw/I1512518_036_S_7023.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1445781_016_S_6949.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1458514_016_S_6971.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  47%|████▋     | 142/299 [00:11<00:12, 12.10it/s]

Saved ADC map to model_data/adni/dti_raw/I1222176_137_S_6794.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1457882_137_S_6903.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I942640_036_S_6134.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  49%|████▉     | 146/299 [00:12<00:13, 11.10it/s]

Saved ADC map to model_data/adni/dti_raw/I1354020_041_S_6292.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I986715_041_S_6292.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I882545_041_S_1418.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  49%|████▉     | 148/299 [00:12<00:12, 11.71it/s]

Saved ADC map to model_data/adni/dti_raw/I1040761_041_S_1418.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1194343_041_S_1418.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1572602_036_S_7070.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  50%|█████     | 150/299 [00:12<00:12, 11.97it/s]

Saved ADC map to model_data/adni/dti_raw/I10298168_041_S_6401.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1008734_041_S_6401.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  52%|█████▏    | 154/299 [00:12<00:12, 11.52it/s]

Saved ADC map to model_data/adni/dti_raw/I1177851_041_S_6401.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1354002_041_S_6401.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1608105_016_S_6941.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  52%|█████▏    | 156/299 [00:13<00:12, 11.87it/s]

Saved ADC map to model_data/adni/dti_raw/I1446310_016_S_6941.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I860963_941_S_5193.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1267867_012_S_4094.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  53%|█████▎    | 158/299 [00:13<00:11, 12.80it/s]

Saved ADC map to model_data/adni/dti_raw/I1574098_114_S_6063.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1355424_114_S_6251.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]

Processing DICOM folders:  54%|█████▍    | 162/299 [00:13<00:11, 12.10it/s]

Saved ADC map to model_data/adni/dti_raw/I1586677_114_S_6251.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1536468_016_S_7039.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1189937_016_S_6771.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  56%|█████▌    | 166/299 [00:13<00:09, 13.31it/s]

Saved ADC map to model_data/adni/dti_raw/I1387535_114_S_6462.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1639410_114_S_6462.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I953651_094_S_4649.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1149060_137_S_6685.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  56%|█████▌    | 168/299 [00:14<00:11, 11.47it/s]

Saved ADC map to model_data/adni/dti_raw/I1219626_041_S_6785.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1555318_041_S_6785.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  57%|█████▋    | 170/299 [00:14<00:10, 11.76it/s]

Saved ADC map to model_data/adni/dti_raw/I1358540_041_S_6785.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1033373_041_S_5100.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I881737_041_S_5100.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  58%|█████▊    | 174/299 [00:14<00:10, 12.40it/s]

Saved ADC map to model_data/adni/dti_raw/I1185885_041_S_5100.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1555302_041_S_5100.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1271696_137_S_6812.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  59%|█████▉    | 176/299 [00:14<00:11, 11.10it/s]

Saved ADC map to model_data/adni/dti_raw/I979823_094_S_6250.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I893053_941_S_6068.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1243841_041_S_4427.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]

Processing DICOM folders:  60%|██████    | 180/299 [00:15<00:09, 11.90it/s]

Saved ADC map to model_data/adni/dti_raw/I915920_041_S_4427.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I913412_041_S_4271.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1072593_041_S_4271.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  61%|██████    | 182/299 [00:15<00:09, 12.28it/s]

Saved ADC map to model_data/adni/dti_raw/I1227855_041_S_4271.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1266574_137_S_4520.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  62%|██████▏   | 184/299 [00:15<00:10, 11.09it/s]

Saved ADC map to model_data/adni/dti_raw/I929135_137_S_4520.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1366984_137_S_4520.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1553549_137_S_4520.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  63%|██████▎   | 188/299 [00:15<00:09, 12.08it/s]

Saved ADC map to model_data/adni/dti_raw/I930431_036_S_4389.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1261620_016_S_6802.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1256814_016_S_6834.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  64%|██████▎   | 190/299 [00:15<00:08, 12.26it/s]

Saved ADC map to model_data/adni/dti_raw/I1606247_016_S_6834.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I848022_002_S_4654.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  64%|██████▍   | 192/299 [00:16<00:09, 10.79it/s]

Saved ADC map to model_data/adni/dti_raw/I1356532_137_S_6883.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I904015_024_S_5290.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I872929_041_S_4876.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  66%|██████▌   | 196/299 [00:16<00:08, 11.73it/s]

Saved ADC map to model_data/adni/dti_raw/I820310_016_S_4951.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1173073_016_S_4951.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I857844_002_S_5178.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  66%|██████▌   | 198/299 [00:16<00:10,  9.84it/s]

Saved ADC map to model_data/adni/dti_raw/I11151524_094_S_6269.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I979941_094_S_6269.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I896828_941_S_4365.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1623788_023_S_6547.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]

Processing DICOM folders:  68%|██████▊   | 203/299 [00:17<00:07, 12.20it/s]

Saved ADC map to model_data/adni/dti_raw/I884973_941_S_6058.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I10298194_041_S_6314.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1371446_041_S_6314.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  69%|██████▊   | 205/299 [00:17<00:07, 12.43it/s]

Saved ADC map to model_data/adni/dti_raw/I989138_041_S_6314.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I921887_941_S_6094.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  69%|██████▉   | 207/299 [00:17<00:08, 11.32it/s]

Saved ADC map to model_data/adni/dti_raw/I1555338_041_S_0679.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I872909_041_S_0679.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1013378_041_S_0679.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  71%|███████   | 212/299 [00:17<00:06, 13.60it/s]

Saved ADC map to model_data/adni/dti_raw/I1177914_041_S_0679.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1529611_023_S_4448.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1373759_016_S_6892.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1344944_114_S_6347.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1589949_023_S_6374.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]

Processing DICOM folders:  72%|███████▏  | 215/299 [00:17<00:05, 15.99it/s]

Saved ADC map to model_data/adni/dti_raw/I23428_016_S_0769.nii
Shape: (37, 128, 128), Spacing: [1.796875, 1.796875, 3.9]
Saved ADC map to model_data/adni/dti_raw/I1507396_036_S_6887.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  73%|███████▎  | 217/299 [00:18<00:06, 13.31it/s]

Saved ADC map to model_data/adni/dti_raw/I1023738_016_S_4902.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1282327_016_S_4902.nii
Shape: (82, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1075143_002_S_4225.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  74%|███████▍  | 221/299 [00:18<00:05, 13.22it/s]

Saved ADC map to model_data/adni/dti_raw/I827367_002_S_4473.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I949933_041_S_6159.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1274608_041_S_6159.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  75%|███████▍  | 223/299 [00:18<00:05, 13.10it/s]

Saved ADC map to model_data/adni/dti_raw/I893577_041_S_5141.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1286976_041_S_6192.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  75%|███████▌  | 225/299 [00:18<00:06, 11.75it/s]

Saved ADC map to model_data/adni/dti_raw/I959651_041_S_6192.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I10298179_041_S_6192.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1350230_041_S_6354.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  77%|███████▋  | 229/299 [00:19<00:05, 12.30it/s]

Saved ADC map to model_data/adni/dti_raw/I1663451_041_S_6354.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1003302_041_S_6354.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I922792_036_S_6099.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  77%|███████▋  | 231/299 [00:19<00:05, 13.15it/s]

Saved ADC map to model_data/adni/dti_raw/I1589374_114_S_6309.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1353784_114_S_6309.nii
Shape: (80, 128, 128), Spacing: [2.671875, 2.671875, 2.0]

Processing DICOM folders:  78%|███████▊  | 233/299 [00:19<00:05, 11.61it/s]

Saved ADC map to model_data/adni/dti_raw/I1219567_041_S_4051.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I872892_041_S_4051.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1611651_023_S_6369.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1533081_036_S_6894.nii
Shape: (81, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  80%|███████▉  | 239/299 [00:19<00:03, 15.69it/s]

Saved ADC map to model_data/adni/dti_raw/I1019232_094_S_6440.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1181932_153_S_6755.nii
Shape: (80, 116, 116), Spacing: [2.5862069129944, 2.5862069129944, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1582518_023_S_6334.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I843519_002_S_1155.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  81%|████████  | 241/299 [00:19<00:04, 13.16it/s]

Saved ADC map to model_data/adni/dti_raw/I963566_024_S_6202.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I913240_941_S_6080.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  81%|████████▏ | 243/299 [00:20<00:04, 13.00it/s]

Saved ADC map to model_data/adni/dti_raw/I852755_941_S_6017.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I927365_036_S_4538.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1522061_016_S_6816.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  83%|████████▎ | 247/299 [00:20<00:03, 13.28it/s]

Saved ADC map to model_data/adni/dti_raw/I1359979_016_S_6816.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1256842_016_S_6816.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1177878_041_S_6731.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  83%|████████▎ | 249/299 [00:20<00:04, 11.85it/s]

Saved ADC map to model_data/adni/dti_raw/I11162085_041_S_6731.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1350261_041_S_6731.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I10249802_041_S_6731.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1594028_023_S_6702.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]

Processing DICOM folders:  85%|████████▍ | 254/299 [00:20<00:03, 13.47it/s]

Saved ADC map to model_data/adni/dti_raw/I915824_137_S_6060.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I986509_094_S_6275.nii
Shape: (80, 116, 116), Spacing: [2.5172414779663, 2.5172414779663, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1413023_016_S_5057.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  86%|████████▌ | 256/299 [00:21<00:03, 12.09it/s]

Saved ADC map to model_data/adni/dti_raw/I1190079_016_S_5057.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1576354_041_S_4200.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  86%|████████▋ | 258/299 [00:21<00:03, 12.22it/s]

Saved ADC map to model_data/adni/dti_raw/I923452_041_S_4200.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1265870_041_S_4200.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1498593_003_S_4288.nii
Shape: (81, 232, 232), Spacing: [1.0, 1.0, 2.0]

Processing DICOM folders:  88%|████████▊ | 262/299 [00:21<00:03, 12.18it/s]

Saved ADC map to model_data/adni/dti_raw/I858863_941_S_4187.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I872981_941_S_6044.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I874870_941_S_6044.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  88%|████████▊ | 264/299 [00:21<00:03, 11.11it/s]

Saved ADC map to model_data/adni/dti_raw/I1116677_137_S_6654.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I835747_002_S_6007.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1557297_116_S_6133.nii
Shape: (1, 81, 116, 116), Spacing: [1.0, 1.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I840242_002_S_6009.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  90%|████████▉ | 269/299 [00:22<00:02, 13.17it/s]

Saved ADC map to model_data/adni/dti_raw/I10899752_016_S_6939.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1444307_016_S_6939.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1003713_024_S_6385.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  91%|█████████ | 271/299 [00:22<00:02, 13.09it/s]

Saved ADC map to model_data/adni/dti_raw/I1683072_041_S_5253.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1227733_041_S_5253.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  91%|█████████▏| 273/299 [00:22<00:02, 11.70it/s]

Saved ADC map to model_data/adni/dti_raw/I1576302_041_S_5253.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I920792_041_S_5253.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1052770_137_S_6576.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  93%|█████████▎| 277/299 [00:22<00:01, 12.43it/s]

Saved ADC map to model_data/adni/dti_raw/I1047869_041_S_6447.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I831859_022_S_5004.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I861972_002_S_6030.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  93%|█████████▎| 279/299 [00:23<00:01, 11.24it/s]

Saved ADC map to model_data/adni/dti_raw/I915143_041_S_4974.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1435742_016_S_6931.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  94%|█████████▍| 281/299 [00:23<00:01, 11.55it/s]

Saved ADC map to model_data/adni/dti_raw/I939368_941_S_4036.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I931970_041_S_4513.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I10216977_041_S_4513.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  95%|█████████▌| 285/299 [00:23<00:01, 12.33it/s]

Saved ADC map to model_data/adni/dti_raw/I1253533_041_S_4513.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1576334_041_S_4513.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I958289_036_S_6189.nii
Shape: (81, 116, 116), Spacing: [2.1724138259888, 2.1724138259888, 2.0]

Processing DICOM folders:  96%|█████████▌| 287/299 [00:23<00:01, 11.04it/s]

Saved ADC map to model_data/adni/dti_raw/I1567967_016_S_6790.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1359952_016_S_6790.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1194308_016_S_6790.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  97%|█████████▋| 291/299 [00:24<00:00, 12.10it/s]

Saved ADC map to model_data/adni/dti_raw/I1634901_016_S_7014.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1439503_137_S_6919.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1151044_016_S_6708.nii
Shape: (82, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  98%|█████████▊| 293/299 [00:24<00:00, 12.45it/s]

Saved ADC map to model_data/adni/dti_raw/I980392_041_S_6226.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1348003_041_S_6226.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing DICOM folders:  99%|█████████▉| 297/299 [00:24<00:00, 13.34it/s]

Saved ADC map to model_data/adni/dti_raw/I893558_941_S_4292.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1142378_022_S_6013.nii
Shape: (40, 180, 180), Spacing: [1.2222222089767, 1.2222222089767, 4.0]
Saved ADC map to model_data/adni/dti_raw/I1220335_094_S_6736.nii
Shape: (85, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I532648_068_S_4340.nii
Shape: (40, 74, 74), Spacing: [3.0, 3.0, 3.0]

Processing DICOM folders: 100%|██████████| 299/299 [00:24<00:00, 12.15it/s]

Saved ADC map to model_data/adni/dti_raw/I926813_137_S_4482.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]
Saved ADC map to model_data/adni/dti_raw/I1246457_137_S_4482.nii
Shape: (80, 116, 116), Spacing: [2.0, 2.0, 2.0]

Processing complete!
Successfully processed: 299
Errors: 0

In [15]:
# Create a numpy array of file paths for files with shape (80, 116, 116)
dti_raw_dir = Path("model_data/adni/dti_raw")

# Get all .nii files (including .nii.gz)
nii_files = list(dti_raw_dir.glob("*.nii")) + list(dti_raw_dir.glob("*.nii.gz"))

# Filter files by shape (80, 116, 116)
valid_file_paths = []

for nii_file in tqdm(nii_files, desc="Checking file shapes"):
    try:
        # Load the NIfTI file
        nii_img = nib.load(str(nii_file))
        data = nii_img.get_fdata()
        
        # Check if shape is (80, 116, 116)
        if data.shape == (80, 116, 116):
            valid_file_paths.append(str(nii_file))
    except Exception as e:
        print(f"\nError loading {nii_file}: {e}")
        continue

# Convert to numpy array
valid_file_paths_array = np.array(valid_file_paths, dtype=object)

print(f"\nFound {len(valid_file_paths_array)} files with shape (80, 116, 116)")
print(f"Total files checked: {len(nii_files)}")

Checking file shapes: 100%|██████████| 299/299 [00:02<00:00, 130.89it/s]

Found 235 files with shape (80, 116, 116)
Total files checked: 299

In [14]:
# Create a numpy array of file paths for T1 MRI files with shape (176, 256, 240)
t1_mri_raw_dir = Path("model_data/adni/t1_mri_raw")

# Get all .nii files (including .nii.gz)
t1_nii_files = list(t1_mri_raw_dir.glob("*.nii")) + list(t1_mri_raw_dir.glob("*.nii.gz"))

# Filter files by shape (176, 256, 240)
t1_valid_file_paths = []

for nii_file in tqdm(t1_nii_files, desc="Checking T1 MRI file shapes"):
    try:
        # Load the NIfTI file
        nii_img = nib.load(str(nii_file))
        data = nii_img.get_fdata()
        
        # Check if shape is (176, 256, 240)
        if data.shape == (176, 256, 240):
            t1_valid_file_paths.append(str(nii_file))
    except Exception as e:
        print(f"\nError loading {nii_file}: {e}")
        continue

# Convert to numpy array
t1_valid_file_paths_array = np.array(t1_valid_file_paths, dtype=object)

print(f"\nFound {len(t1_valid_file_paths_array)} T1 MRI files with shape (176, 256, 240)")
print(f"Total T1 MRI files checked: {len(t1_nii_files)}")

Checking T1 MRI file shapes: 100%|██████████| 294/294 [00:18<00:00, 15.84it/s]

Found 236 T1 MRI files with shape (176, 256, 240)
Total T1 MRI files checked: 294

In [16]:
# Compare subjects in T1 MRI and DTI arrays to find the difference
import re

# Extract subject IDs from file paths
def extract_subject_id(path):
    """Extract subject ID from path like '.../I[image_id]_[subject_id].nii'"""
    filename = Path(path).name
    # Pattern: I[image_id]_[subject_id].nii
    match = re.search(r'I\d+_(.+?)\.nii', filename)
    if match:
        return match.group(1)
    return None

In [17]:
# Create filtered arrays with only files from common subjects
import re

# Extract subject ID from file path
def extract_subject_id(path):
    """Extract subject ID from path like '.../I[image_id]_[subject_id].nii'"""
    filename = Path(path).name
    match = re.search(r'I\d+_(.+?)\.nii', filename)
    if match:
        return match.group(1)
    return None

# Get common subjects (from previous cell output: 129 common subjects)
# We'll recalculate to be sure
t1_subjects = set()
for path in t1_valid_file_paths_array:
    subject_id = extract_subject_id(path)
    if subject_id:
        t1_subjects.add(subject_id)

dti_subjects = set()
for path in valid_file_paths_array:
    subject_id = extract_subject_id(path)
    if subject_id:
        dti_subjects.add(subject_id)

common_subjects = t1_subjects & dti_subjects

print(f"Common subjects: {len(common_subjects)}")

# Filter T1 MRI files to only include common subjects
t1_common_files = []
for path in t1_valid_file_paths_array:
    subject_id = extract_subject_id(path)
    if subject_id and subject_id in common_subjects:
        t1_common_files.append(path)

# Filter DTI files to only include common subjects
dti_common_files = []
for path in valid_file_paths_array:
    subject_id = extract_subject_id(path)
    if subject_id and subject_id in common_subjects:
        dti_common_files.append(path)

# Create numpy arrays
t1_common_array = np.array(t1_common_files, dtype=object)
dti_common_array = np.array(dti_common_files, dtype=object)

print(f"\nT1 MRI files with common subjects: {len(t1_common_array)}")
print(f"DTI files with common subjects: {len(dti_common_array)}")

Common subjects: 129

T1 MRI files with common subjects: 202
DTI files with common subjects: 213

In [24]:
# Extract subject IDs from T1 MRI files
t1_subjects = set()
for path in t1_valid_file_paths_array:
    subject_id = extract_subject_id(path)
    if subject_id:
        t1_subjects.add(subject_id)

# Extract subject IDs from DTI files
dti_subjects = set()
for path in valid_file_paths_array:
    subject_id = extract_subject_id(path)
    if subject_id:
        dti_subjects.add(subject_id)

# Find differences
t1_only = t1_subjects - dti_subjects
dti_only = dti_subjects - t1_subjects
common_subjects = t1_subjects & dti_subjects

print(f"T1 MRI files: {len(t1_valid_file_paths_array)}")
print(f"DTI files: {len(valid_file_paths_array)}")
print()
print(f"Unique subjects in T1 MRI: {len(t1_subjects)}")
print(f"Unique subjects in DTI: {len(dti_subjects)}")
print(f"Common subjects: {len(common_subjects)}")

T1 MRI files: 236
DTI files: 235

Unique subjects in T1 MRI: 154
Unique subjects in DTI: 146
Common subjects: 129

In [25]:
if t1_only:
    print(f"Subjects in T1 MRI but NOT in DTI ({len(t1_only)}):")
    for subject in sorted(t1_only):
        # Find the T1 file for this subject
        t1_files = [p for p in t1_valid_file_paths_array if subject in Path(p).name]
        print(f"  {subject}: {t1_files[0] if t1_files else 'No file found'}")

if dti_only:
    print(f"\nSubjects in DTI but NOT in T1 MRI ({len(dti_only)}):")
    for subject in sorted(dti_only):
        # Find the DTI file for this subject
        dti_files = [p for p in valid_file_paths_array if subject in Path(p).name]
        print(f"  {subject}: {dti_files[0] if dti_files else 'No file found'}")

if not t1_only and not dti_only:
    print("All subjects match! The difference must be in multiple files per subject.")
    
    # Check for subjects with multiple files
    from collections import Counter
    
    t1_subject_counts = Counter([extract_subject_id(p) for p in t1_valid_file_paths_array if extract_subject_id(p)])
    dti_subject_counts = Counter([extract_subject_id(p) for p in valid_file_paths_array if extract_subject_id(p)])
    
    # Find subjects with different file counts
    print("\nChecking for subjects with different file counts:")
    all_subjects = t1_subject_counts.keys() | dti_subject_counts.keys()
    differences = []
    
    for subject in sorted(all_subjects):
        t1_count = t1_subject_counts.get(subject, 0)
        dti_count = dti_subject_counts.get(subject, 0)
        if t1_count != dti_count:
            differences.append((subject, t1_count, dti_count))
            print(f"  {subject}: T1={t1_count} files, DTI={dti_count} files")
            
            # Show the actual files
            t1_files = [p for p in t1_valid_file_paths_array if subject in Path(p).name]
            dti_files = [p for p in valid_file_paths_array if subject in Path(p).name]
            print(f"    T1 files: {[Path(p).name for p in t1_files]}")
            print(f"    DTI files: {[Path(p).name for p in dti_files]}")
    
    if not differences:
        print("  No differences found in subject file counts.")

Subjects in T1 MRI but NOT in DTI (25):
  003_S_4288: model_data/adni/t1_mri_raw/I1498579_003_S_4288.nii
  016_S_6708: model_data/adni/t1_mri_raw/I1151022_016_S_6708.nii
  022_S_6013: model_data/adni/t1_mri_raw/I1142379_022_S_6013.nii
  036_S_2380: model_data/adni/t1_mri_raw/I1023430_036_S_2380.nii
  036_S_4491: model_data/adni/t1_mri_raw/I984343_036_S_4491.nii
  036_S_6179: model_data/adni/t1_mri_raw/I957103_036_S_6179.nii
  036_S_6189: model_data/adni/t1_mri_raw/I958275_036_S_6189.nii
  036_S_6231: model_data/adni/t1_mri_raw/I973656_036_S_6231.nii
  036_S_6316: model_data/adni/t1_mri_raw/I991861_036_S_6316.nii
  036_S_6466: model_data/adni/t1_mri_raw/I1059028_036_S_6466.nii
  073_S_4777: model_data/adni/t1_mri_raw/I351121_073_S_4777.nii
  094_S_6736: model_data/adni/t1_mri_raw/I1220298_094_S_6736.nii
  114_S_2392: model_data/adni/t1_mri_raw/I1399029_114_S_2392.nii
  114_S_6057: model_data/adni/t1_mri_raw/I1581805_114_S_6057.nii
  114_S_6063: model_data/adni/t1_mri_raw/I1574100_114_S_6063.nii
  114_S_6113: model_data/adni/t1_mri_raw/I1572549_114_S_6113.nii
  114_S_6251: model_data/adni/t1_mri_raw/I1586680_114_S_6251.nii
  114_S_6309: model_data/adni/t1_mri_raw/I1353787_114_S_6309.nii
  114_S_6347: model_data/adni/t1_mri_raw/I1344946_114_S_6347.nii
  114_S_6429: model_data/adni/t1_mri_raw/I1667466_114_S_6429.nii
  114_S_6462: model_data/adni/t1_mri_raw/I1639411_114_S_6462.nii
  114_S_6487: model_data/adni/t1_mri_raw/I1387180_114_S_6487.nii
  114_S_6524: model_data/adni/t1_mri_raw/I1387553_114_S_6524.nii
  114_S_6597: model_data/adni/t1_mri_raw/I1335369_114_S_6597.nii
  114_S_6917: model_data/adni/t1_mri_raw/I1438743_114_S_6917.nii

Subjects in DTI but NOT in T1 MRI (17):
  094_S_6468: model_data/adni/dti_raw/I1024406_094_S_6468.nii
  137_S_4631: model_data/adni/dti_raw/I1417012_137_S_4631.nii
  137_S_4862: model_data/adni/dti_raw/I1056770_137_S_4862.nii
  137_S_6557: model_data/adni/dti_raw/I1043642_137_S_6557.nii
  137_S_6576: model_data/adni/dti_raw/I1052770_137_S_6576.nii
  137_S_6654: model_data/adni/dti_raw/I1116677_137_S_6654.nii
  137_S_6659: model_data/adni/dti_raw/I1120048_137_S_6659.nii
  137_S_6685: model_data/adni/dti_raw/I1149060_137_S_6685.nii
  137_S_6693: model_data/adni/dti_raw/I1213954_137_S_6693.nii
  137_S_6794: model_data/adni/dti_raw/I1222176_137_S_6794.nii
  137_S_6812: model_data/adni/dti_raw/I1271696_137_S_6812.nii
  137_S_6826: model_data/adni/dti_raw/I1242441_137_S_6826.nii
  137_S_6880: model_data/adni/dti_raw/I1360098_137_S_6880.nii
  137_S_6883: model_data/adni/dti_raw/I1356532_137_S_6883.nii
  137_S_6903: model_data/adni/dti_raw/I1457882_137_S_6903.nii
  137_S_6906: model_data/adni/dti_raw/I1454387_137_S_6906.nii
  137_S_6919: model_data/adni/dti_raw/I1439503_137_S_6919.nii

In [20]:
# Create dataframes for DTI and T1 MRI with file info including dates
import re
from datetime import datetime

def extract_info_from_filename(filename):
    """Extract image_id and subject_id from filename like 'I[image_id]_[subject_id].nii'"""
    match = re.match(r'I(\d+)_(.+?)\.nii', filename)
    if match:
        return match.group(1), match.group(2)
    return None, None

def find_date_from_dicom_folder(image_id, subject_id, base_dir):
    """Find the date from the original DICOM folder structure"""
    # Search for the I[image_id] folder for this subject
    subject_dir = base_dir / subject_id
    if not subject_dir.exists():
        return None
    
    # Search recursively for the I[image_id] folder
    for i_folder in subject_dir.rglob(f"I{image_id}"):
        if i_folder.is_dir():
            # Get the parent directory which should contain the date
            date_folder = i_folder.parent
            date_str = date_folder.name
            # Date format: 2017-03-13_14_12_25.0 or similar
            try:
                # Extract just the date part (before the time)
                date_part = date_str.split('_')[0]
                # Try to parse it
                datetime.strptime(date_part, '%Y-%m-%d')
                return date_str
            except:
                # If parsing fails, return the folder name anyway
                return date_str
    return None

In [21]:
# Process DTI files
dti_base_dir = Path("model_data/adni/dti_dcm")
dti_raw_dir = Path("model_data/adni/dti_raw")
dti_files = list(dti_raw_dir.glob("*.nii")) + list(dti_raw_dir.glob("*.nii.gz"))

dti_data = []
for nii_file in tqdm(dti_files, desc="Processing DTI files"):
    filename = nii_file.name
    image_id, subject_id = extract_info_from_filename(filename)
    
    if image_id and subject_id:
        # Find date from original DICOM folder
        date_taken = find_date_from_dicom_folder(image_id, subject_id, dti_base_dir)
        
        dti_data.append({
            'file_name': filename,
            'file_path': str(nii_file),
            'image_id': image_id,
            'subject_id': subject_id,
            'date_taken': date_taken
        })

dti_df = pd.DataFrame(dti_data)
print(f"DTI DataFrame: {len(dti_df)} files")
print(f"\nDTI DataFrame columns: {dti_df.columns.tolist()}")
print(f"\nFirst few rows:")
dti_df.head()

Processing DTI files: 100%|██████████| 299/299 [00:00<00:00, 2741.63it/s]

DTI DataFrame: 299 files

DTI DataFrame columns: ['file_name', 'file_path', 'image_id', 'subject_id', 'date_taken']

First few rows:

,file_name,file_path,image_id,subject_id,date_taken
0,I1223070_012_S_4188.nii,model_data/adni/dti_raw/I1223070_012_S_4188.nii,1223070,012_S_4188,2019-09-04_09_54_08.0
1,I893053_941_S_6068.nii,model_data/adni/dti_raw/I893053_941_S_6068.nii,893053,941_S_6068,2017-08-21_18_31_11.0
2,I980392_041_S_6226.nii,model_data/adni/dti_raw/I980392_041_S_6226.nii,980392,041_S_6226,2018-03-29_13_21_31.0
3,I1043642_137_S_6557.nii,model_data/adni/dti_raw/I1043642_137_S_6557.nii,1043642,137_S_6557,2018-08-28_17_13_57.0
4,I879765_041_S_4143.nii,model_data/adni/dti_raw/I879765_041_S_4143.nii,879765,041_S_4143,2017-07-27_13_27_20.0

In [22]:
# Process T1 MRI files
t1_base_dir = Path("model_data/adni/t1_mri_dcm")
t1_raw_dir = Path("model_data/adni/t1_mri_raw")
t1_files = list(t1_raw_dir.glob("*.nii")) + list(t1_raw_dir.glob("*.nii.gz"))

t1_data = []
for nii_file in tqdm(t1_files, desc="Processing T1 MRI files"):
    filename = nii_file.name
    image_id, subject_id = extract_info_from_filename(filename)
    
    if image_id and subject_id:
        # Find date from original DICOM folder
        date_taken = find_date_from_dicom_folder(image_id, subject_id, t1_base_dir)
        
        t1_data.append({
            'file_name': filename,
            'file_path': str(nii_file),
            'image_id': image_id,
            'subject_id': subject_id,
            'date_taken': date_taken
        })

t1_df = pd.DataFrame(t1_data)
print(f"\n\nT1 MRI DataFrame: {len(t1_df)} files")
print(f"\nT1 MRI DataFrame columns: {t1_df.columns.tolist()}")
print(f"\nFirst few rows:")
t1_df.head()

Processing T1 MRI files: 100%|██████████| 294/294 [00:00<00:00, 2700.54it/s]

T1 MRI DataFrame: 294 files

T1 MRI DataFrame columns: ['file_name', 'file_path', 'image_id', 'subject_id', 'date_taken']

First few rows:

,file_name,file_path,image_id,subject_id,date_taken
0,I1413030_016_S_5057.nii,model_data/adni/t1_mri_raw/I1413030_016_S_5057...,1413030,016_S_5057,2021-02-19_13_16_36.0
1,I1493847_016_S_7002.nii,model_data/adni/t1_mri_raw/I1493847_016_S_7002...,1493847,016_S_7002,2021-09-14_15_36_50.0
2,I904007_024_S_5290.nii,model_data/adni/t1_mri_raw/I904007_024_S_5290.nii,904007,024_S_5290,2017-09-12_08_00_50.0
3,I916492_036_S_6088.nii,model_data/adni/t1_mri_raw/I916492_036_S_6088.nii,916492,036_S_6088,2017-10-12_10_18_44.0
4,I1634890_016_S_7014.nii,model_data/adni/t1_mri_raw/I1634890_016_S_7014...,1634890,016_S_7014,2021-11-30_12_04_08.0

In [25]:
# Create paired dataset for common subjects
# Match DTI and T1 MRI images by date similarity, maximizing pairs

from datetime import datetime
from collections import defaultdict

def parse_date(date_str):
    """Parse date string like '2017-03-13_14_12_25.0' to datetime"""
    if pd.isna(date_str) or date_str is None:
        return None
    try:
        # Extract date part (before first underscore after date)
        date_part = str(date_str).split('_')[0]
        return datetime.strptime(date_part, '%Y-%m-%d')
    except:
        return None

def date_difference(date1, date2):
    """Calculate absolute difference in days between two dates"""
    if date1 is None or date2 is None:
        return float('inf')  # Large penalty for missing dates
    return abs((date1 - date2).days)

def match_images_by_date(dti_images, t1_images):
    """
    Match DTI and T1 images by date similarity using greedy algorithm.
    Returns list of pairs (dti_idx, t1_idx) maximizing matches.
    """
    if len(dti_images) == 0 or len(t1_images) == 0:
        return []
    
    # Parse dates for all images
    dti_dates = [parse_date(d['date_taken']) for d in dti_images]
    t1_dates = [parse_date(t['date_taken']) for t in t1_images]
    
    # Create list of all possible pairs with their date differences
    pairs = []
    for i, dti_img in enumerate(dti_images):
        for j, t1_img in enumerate(t1_images):
            diff = date_difference(dti_dates[i], t1_dates[j])
            pairs.append((diff, i, j))
    
    # Sort by date difference (smallest first)
    pairs.sort(key=lambda x: x[0])
    
    # Greedy matching: take pairs with smallest date differences
    # ensuring each image is used only once
    matched_dti = set()
    matched_t1 = set()
    matches = []
    
    for diff, dti_idx, t1_idx in pairs:
        if dti_idx not in matched_dti and t1_idx not in matched_t1:
            matches.append((dti_idx, t1_idx))
            matched_dti.add(dti_idx)
            matched_t1.add(t1_idx)
    
    return matches

In [26]:
# Filter dataframes to only common subjects
common_subjects_set = set(common_subjects)  # From previous cell

dti_common = dti_df[dti_df['subject_id'].isin(common_subjects_set)].copy()
t1_common = t1_df[t1_df['subject_id'].isin(common_subjects_set)].copy()

print(f"DTI files for common subjects: {len(dti_common)}")
print(f"T1 MRI files for common subjects: {len(t1_common)}")

DTI files for common subjects: 217
T1 MRI files for common subjects: 212

In [40]:
# Diagnostic: Verify pairing logic and check for duplicate usage
print("=== DIAGNOSTIC ANALYSIS ===\n")

# Verify counts
print("1. File Counts:")
print(f"   DTI files for common subjects: {len(dti_common)}")
print(f"   T1 MRI files for common subjects: {len(t1_common)}")
print(f"   Total pairs created: {len(paired_df)}")
print(f"   Maximum possible pairs (min of both): {min(len(dti_common), len(t1_common))}")
print()

# Check if any DTI images are used multiple times
dti_paths_in_pairs = paired_df['dti_file_path'].tolist()
dti_duplicates = [path for path in dti_paths_in_pairs if dti_paths_in_pairs.count(path) > 1]

print("2. Duplicate DTI Usage:")
if dti_duplicates:
    print(f"   WARNING: {len(set(dti_duplicates))} unique DTI files used multiple times!")
    for dup_path in set(dti_duplicates):
        count = dti_paths_in_pairs.count(dup_path)
        print(f"   {Path(dup_path).name}: used {count} times")
else:
    print("   ✓ No DTI files used multiple times")
print()

# Check if any T1 images are used multiple times
t1_paths_in_pairs = paired_df['t1_file_path'].tolist()
t1_duplicates = [path for path in t1_paths_in_pairs if t1_paths_in_pairs.count(path) > 1]

print("3. Duplicate T1 Usage:")
if t1_duplicates:
    print(f"   WARNING: {len(set(t1_duplicates))} unique T1 files used multiple times!")
    for dup_path in set(t1_duplicates):
        count = t1_paths_in_pairs.count(dup_path)
        print(f"   {Path(dup_path).name}: used {count} times")
else:
    print("   ✓ No T1 files used multiple times")
print()

# Check unique files used
unique_dti_used = len(set(dti_paths_in_pairs))
unique_t1_used = len(set(t1_paths_in_pairs))

print("4. Unique Files Used:")
print(f"   Unique DTI files in pairs: {unique_dti_used} (out of {len(dti_common)} total)")
print(f"   Unique T1 files in pairs: {unique_t1_used} (out of {len(t1_common)} total)")
print()

# Check subjects with multiple pairs
print("5. Subjects with Multiple Pairs:")
subject_pair_counts = paired_df['subject_id'].value_counts()
multi_pair_subjects = subject_pair_counts[subject_pair_counts > 1]
print(f"   Subjects with >1 pair: {len(multi_pair_subjects)}")
if len(multi_pair_subjects) > 0:
    print(f"   Max pairs per subject: {subject_pair_counts.max()}")
    print(f"   Example subjects with multiple pairs:")
    for subject, count in multi_pair_subjects.head(5).items():
        print(f"     {subject}: {count} pairs")
        # Show the pairs for this subject
        subject_pairs = paired_df[paired_df['subject_id'] == subject]
        for idx, row in subject_pairs.iterrows():
            print(f"       Pair: DTI={Path(row['dti_file_path']).name} (date: {row['dti_date_taken']}) "
                  f"<-> T1={Path(row['t1_file_path']).name} (date: {row['t1_date_taken']})")
print()

# Verify the matching logic by checking a specific subject
print("6. Detailed Check for One Subject:")
example_subject = subject_pair_counts.index[0] if len(subject_pair_counts) > 0 else None
if example_subject:
    print(f"   Subject: {example_subject}")
    subject_dti = [d for d in dti_by_subject[example_subject]]
    subject_t1 = [t for t in t1_by_subject[example_subject]]
    print(f"   DTI images for this subject: {len(subject_dti)}")
    print(f"   T1 images for this subject: {len(subject_t1)}")
    print(f"   Pairs created for this subject: {subject_pair_counts[example_subject]}")
    
    # Show all DTI and T1 images
    print(f"   DTI images:")
    for d in subject_dti:
        print(f"     {d['file_name']} (date: {d['date_taken']})")
    print(f"   T1 images:")
    for t in subject_t1:
        print(f"     {t['file_name']} (date: {t['date_taken']})")
    
    # Show which ones were paired
    subject_pairs = paired_df[paired_df['subject_id'] == example_subject]
    print(f"   Paired:")
    for idx, row in subject_pairs.iterrows():
        print(f"     {Path(row['dti_file_path']).name} <-> {Path(row['t1_file_path']).name}")

print("\n=== END DIAGNOSTIC ===")

=== DIAGNOSTIC ANALYSIS ===

1. File Counts:
   DTI files for common subjects: 217
   T1 MRI files for common subjects: 212
   Total pairs created: 212
   Maximum possible pairs (min of both): 212

2. Duplicate DTI Usage:
   ✓ No DTI files used multiple times

3. Duplicate T1 Usage:
   ✓ No T1 files used multiple times

4. Unique Files Used:
   Unique DTI files in pairs: 212 (out of 217 total)
   Unique T1 files in pairs: 212 (out of 212 total)

5. Subjects with Multiple Pairs:
   Subjects with >1 pair: 51
   Max pairs per subject: 4
   Example subjects with multiple pairs:
     041_S_5100: 4 pairs
       Pair: DTI=I1555302_041_S_5100.nii (date: 2022-02-21_14_37_11.0) <-> T1=I1555295_041_S_5100.nii (date: 2022-02-21_14_02_53.0)
       Pair: DTI=I1185885_041_S_5100.nii (date: 2019-07-11_12_44_59.0) <-> T1=I1185877_041_S_5100.nii (date: 2019-07-11_12_06_22.0)
       Pair: DTI=I1033373_041_S_5100.nii (date: 2018-08-08_14_11_21.0) <-> T1=I1033364_041_S_5100.nii (date: 2018-08-08_13_42_32.0)
       Pair: DTI=I881737_041_S_5100.nii (date: 2017-07-31_16_38_08.0) <-> T1=I881729_041_S_5100.nii (date: 2017-07-31_15_37_15.0)
     041_S_4874: 4 pairs
       Pair: DTI=I1046075_041_S_4874.nii (date: 2018-09-06_14_44_47.0) <-> T1=I1046066_041_S_4874.nii (date: 2018-09-06_14_08_35.0)
       Pair: DTI=I1576316_041_S_4874.nii (date: 2022-03-29_10_44_02.0) <-> T1=I1576310_041_S_4874.nii (date: 2022-03-29_10_15_05.0)
       Pair: DTI=I884460_041_S_4874.nii (date: 2017-08-04_14_21_50.0) <-> T1=I884453_041_S_4874.nii (date: 2017-08-04_13_35_09.0)
       Pair: DTI=I1213049_041_S_4874.nii (date: 2019-08-15_11_39_48.0) <-> T1=I1213040_041_S_4874.nii (date: 2019-08-15_11_06_41.0)
     041_S_4513: 4 pairs
       Pair: DTI=I10216977_041_S_4513.nii (date: 2023-05-09_11_45_22.0) <-> T1=I10216986_041_S_4513.nii (date: 2023-05-09_11_23_17.0)
       Pair: DTI=I931970_041_S_4513.nii (date: 2017-11-16_11_53_44.0) <-> T1=I931962_041_S_4513.nii (date: 2017-11-16_10_18_58.0)
       Pair: DTI=I1253533_041_S_4513.nii (date: 2019-11-05_12_09_29.0) <-> T1=I1253525_041_S_4513.nii (date: 2019-11-05_11_24_49.0)
       Pair: DTI=I1576334_041_S_4513.nii (date: 2022-04-05_10_05_35.0) <-> T1=I1576327_041_S_4513.nii (date: 2022-04-05_09_36_30.0)
     137_S_4536: 4 pairs
       Pair: DTI=I1370479_137_S_4536.nii (date: 2020-11-17_15_07_22.0) <-> T1=I1370463_137_S_4536.nii (date: 2020-11-17_14_36_35.0)
       Pair: DTI=I1257073_137_S_4536.nii (date: 2019-11-15_16_35_13.0) <-> T1=I1257058_137_S_4536.nii (date: 2019-11-15_16_09_56.0)
       Pair: DTI=I925992_137_S_4536.nii (date: 2017-11-02_13_48_22.0) <-> T1=I925981_137_S_4536.nii (date: 2017-11-02_13_22_02.0)
       Pair: DTI=I1070900_137_S_4536.nii (date: 2018-11-07_14_32_14.0) <-> T1=I1070885_137_S_4536.nii (date: 2018-11-07_14_07_08.0)
     041_S_6731: 4 pairs
       Pair: DTI=I10249802_041_S_6731.nii (date: 2023-07-31_11_48_23.0) <-> T1=I10249811_041_S_6731.nii (date: 2023-07-31_11_27_10.0)
       Pair: DTI=I1350261_041_S_6731.nii (date: 2020-10-16_12_55_27.0) <-> T1=I1350252_041_S_6731.nii (date: 2020-10-16_12_27_33.0)
       Pair: DTI=I11162085_041_S_6731.nii (date: 2022-06-27_12_53_56.0) <-> T1=I11162094_041_S_6731.nii (date: 2022-06-27_12_32_40.0)
       Pair: DTI=I1177878_041_S_6731.nii (date: 2019-05-28_10_19_41.0) <-> T1=I1177870_041_S_6731.nii (date: 2019-05-28_09_40_22.0)

6. Detailed Check for One Subject:
   Subject: 041_S_5100
   DTI images for this subject: 4
   T1 images for this subject: 4
   Pairs created for this subject: 4
   DTI images:
     I1555302_041_S_5100.nii (date: 2022-02-21_14_37_11.0)
     I1185885_041_S_5100.nii (date: 2019-07-11_12_44_59.0)
     I1033373_041_S_5100.nii (date: 2018-08-08_14_11_21.0)
     I881737_041_S_5100.nii (date: 2017-07-31_16_38_08.0)
   T1 images:
     I1033364_041_S_5100.nii (date: 2018-08-08_13_42_32.0)
     I1185877_041_S_5100.nii (date: 2019-07-11_12_06_22.0)
     I1555295_041_S_5100.nii (date: 2022-02-21_14_02_53.0)
     I881729_041_S_5100.nii (date: 2017-07-31_15_37_15.0)
   Paired:
     I1555302_041_S_5100.nii <-> I1555295_041_S_5100.nii
     I1185885_041_S_5100.nii <-> I1185877_041_S_5100.nii
     I1033373_041_S_5100.nii <-> I1033364_041_S_5100.nii
     I881737_041_S_5100.nii <-> I881729_041_S_5100.nii

=== END DIAGNOSTIC ===

In [29]:
# Group by subject
dti_by_subject = defaultdict(list)
t1_by_subject = defaultdict(list)

for _, row in dti_common.iterrows():
    dti_by_subject[row['subject_id']].append({
        'file_path': row['file_path'],
        'file_name': row['file_name'],
        'image_id': row['image_id'],
        'date_taken': row['date_taken']
    })

for _, row in t1_common.iterrows():
    t1_by_subject[row['subject_id']].append({
        'file_path': row['file_path'],
        'file_name': row['file_name'],
        'image_id': row['image_id'],
        'date_taken': row['date_taken']
    })

In [30]:
# Create pairs for each subject
paired_data = []

for subject_id in tqdm(sorted(common_subjects_set), desc="Matching images by date"):
    dti_images = dti_by_subject[subject_id]
    t1_images = t1_by_subject[subject_id]
    
    if len(dti_images) == 0 or len(t1_images) == 0:
        continue
    
    # Match images by date similarity
    matches = match_images_by_date(dti_images, t1_images)
    
    # Create pairs
    for dti_idx, t1_idx in matches:
        dti_img = dti_images[dti_idx]
        t1_img = t1_images[t1_idx]
        
        paired_data.append({
            'subject_id': subject_id,
            'dti_file_path': dti_img['file_path'],
            'dti_file_name': dti_img['file_name'],
            'dti_image_id': dti_img['image_id'],
            'dti_date_taken': dti_img['date_taken'],
            't1_file_path': t1_img['file_path'],
            't1_file_name': t1_img['file_name'],
            't1_image_id': t1_img['image_id'],
            't1_date_taken': t1_img['date_taken']
        })

Matching images by date: 100%|██████████| 129/129 [00:00<00:00, 68978.23it/s]

In [31]:
# Create dataframe
paired_df = pd.DataFrame(paired_data)

print(f"\n\nPaired Dataset Summary:")
print(f"Total pairs created: {len(paired_df)}")
print(f"Unique subjects with pairs: {paired_df['subject_id'].nunique()}")
print(f"\nPairs per subject distribution:")
print(paired_df['subject_id'].value_counts().value_counts().sort_index())

Paired Dataset Summary:
Total pairs created: 212
Unique subjects with pairs: 129

Pairs per subject distribution:
count
1    78
2    28
3    14
4     9
Name: count, dtype: int64

In [50]:
# Add "I" prefix if not already present
paired_df['dti_image_id'] = paired_df['dti_image_id'].apply(lambda x: f"I{x}" if not str(x).startswith('I') else x)
paired_df['t1_image_id'] = paired_df['t1_image_id'].apply(lambda x: f"I{x}" if not str(x).startswith('I') else x)

In [5]:
# Add group labels from CSV to paired_df
# Read the labels CSV file
labels_df = pd.read_csv("/Users/william.wakefield/PycharmProjects/ADRU/model_data/adni/t1MRI_labels_matched.csv")

# Create a mapping from Image Data ID to Group
# The Image Data ID column contains the T1 MRI image IDs
image_id_to_group = dict(zip(labels_df['Image Data ID'], labels_df['Group']))

print(f"\nImage ID to Group mapping created: {len(image_id_to_group)} entries")

Image ID to Group mapping created: 295 entries

In [55]:
# Match T1 image IDs from paired_df to get groups
# paired_df has 't1_image_id' column
paired_df['group'] = paired_df['t1_image_id'].map(image_id_to_group)

In [67]:
# Add label column to paired_df
# SMC and CN -> 0, everything else -> 1
paired_df['label'] = paired_df['group'].apply(lambda x: 0 if x in ['CN'] else 1)

In [15]:
paired_df_sep = paired_df[paired_df['group'].isin(['CN', 'AD'])].copy()
paired_df_sep['label_sep'] = paired_df_sep['group'].map({'CN': 0, 'AD': 1})

In [64]:
pd.DataFrame.to_csv(paired_df, "model_data/adni/paired_df_full.csv")

In [2]:
paired_df = pd.read_csv("model_data/adni/paired_df_full.csv", index_col=0)

In [ ]:
paired_df['dti_rotated_file_path'] = paired_df['dti_file_path'].str.replace('dti_raw', 'dti_rotated', regex=False)
paired_df['t1_rotated_file_path'] = paired_df['t1_file_path'].str.replace('t1_mri_raw', 't1_rotated', regex=False)

In [6]:
# Setup directories for registered and masked images
dti_reg_dir = Path("model_data/adni/dti_registered")
dti_masked_dir = Path("model_data/adni/dti_masked")
t1_reg_dir = Path("model_data/adni/t1_registered")
t1_masked_dir = Path("model_data/adni/t1_masked")

In [53]:
fixed = ants.image_read('model_data/mni_t1.nii')

In [40]:
wm_mask = nilearn.datasets.load_mni152_wm_mask()
gm_mask = nilearn.datasets.load_mni152_gm_mask()

In [52]:
in_dir = "model_data/adni/t1_mri_raw"
out_dir = "model_data/adni/t1_rotated"

def rot_x90_y180_z180(a):
    if a.ndim == 4:
        a = np.transpose(a, (0, 2, 1, 3))  # (X, Z, Y, T) - 90° on X
        a = np.flip(a, axis=2)              # -Y (completes 90° on X)
        a = np.flip(a, axis=0)              # -X (180° on Y)
        a = np.flip(a, axis=0)              # -X (180° on Z)
        a = np.flip(a, axis=1)              # -Z (180° on Z)
    else:
        a = np.transpose(a, (0, 2, 1))      # (X, Z, Y) - 90° on X
        a = np.flip(a, axis=2)              # -Y (completes 90° on X)
        a = np.flip(a, axis=0)              # -X (180° on Y)
        a = np.flip(a, axis=0)              # -X (180° on Z)
        a = np.flip(a, axis=1)              # -Z (180° on Z)
    return a

for fname in tqdm(f for f in os.listdir(in_dir) if f.endswith((".nii"))):
    nii = nib.load(os.path.join(in_dir, fname))
    data = rot_x90_y180_z180(nii.get_fdata())
    nib.save(
        nib.Nifti1Image(data, nii.affine, nii.header),
        os.path.join(out_dir, fname)
    )

294it [00:30,  9.71it/s]

In [60]:
t1_registered = []

for idx, row in tqdm(paired_df.iterrows(), total=len(paired_df),
    desc="Registering T1 to MNI"):
    t1_in_path = Path(row["t1_rotated_file_path"])

    t1_out_path = t1_reg_dir / t1_in_path.name

    # 1) Register subject T1 to MNI T1
    moving_t1 = ants.image_read(str(t1_in_path))
    reg_t1_to_mni = ants.registration(fixed=fixed, moving=moving_t1, type_of_transform="SyN")

    # Save T1 in MNI space
    ants.image_write(reg_t1_to_mni["warpedmovout"], str(t1_out_path))
    t1_registered.append(str(t1_out_path))

Registering T1 to MNI: 100%|██████████| 212/212 [41:58<00:00, 11.88s/it]

In [59]:
dti_registered = []

for idx, row in tqdm(paired_df.iterrows(), total=len(paired_df),
    desc="Registering ADC to MNI"):
    dti_in_path = Path(row["dti_rotated_file_path"])
    dti_out_path = dti_reg_dir / dti_in_path.name

    # 2) Register subject ADC (DTI) to MNI t1 space
    moving_adc = ants.image_read(str(dti_in_path))
    reg_adc_to_mni = ants.registration(fixed=fixed, moving=moving_adc, type_of_transform="SyN")
    
    # Save ADC in MNI space
    ants.image_write(reg_adc_to_mni["warpedmovout"], str(dti_out_path))
    dti_registered.append(str(dti_out_path))

Registering ADC to MNI: 100%|██████████| 212/212 [09:47<00:00,  2.77s/it]

####New 802 pairs data

In [6]:
raw_dir = Path("model_data/adni/t1_long_data/t1_long_raw")
reg_dir = Path("model_data/adni/t1_long_data/t1_long_registered")
fixed = ants.image_read("model_data/mni_t1.nii")

def rot_x90_yneg180(a):
    """Apply +90° rotation around X axis, then -180° around Y axis."""
    a = np.transpose(a, (0, 2, 1))
    a = np.flip(a, axis=1)
    a = np.flip(a, axis=0)
    a = np.flip(a, axis=2)
    return a

nii_files = sorted(f for f in os.listdir(raw_dir) if f.endswith(".nii"))

In [28]:
for fname in tqdm(nii_files, desc="Orient + Register T1 to MNI"):
    out_path = reg_dir / fname

    nii = nib.load(str(raw_dir / fname))
    data = rot_x90_yneg180(nii.get_fdata())
    oriented_nii = nib.Nifti1Image(data, nii.affine, nii.header)

    with tempfile.NamedTemporaryFile(suffix=".nii", delete=False) as tmp:
        tmp_path = tmp.name
    nib.save(oriented_nii, tmp_path)

    moving = ants.image_read(tmp_path)
    reg = ants.registration(fixed=fixed, moving=moving, type_of_transform="SyN")
    ants.image_write(reg["warpedmovout"], str(out_path))

    os.unlink(tmp_path)

Orient + Register T1 to MNI: 100%|██████████| 802/802 [49:54<00:00,  3.73s/it]

In [23]:
FSLDIR = os.environ.get("FSLDIR", os.path.expanduser("~/fsl"))
FSL_BIN = os.path.join(FSLDIR, "share", "fsl", "bin")


def _fsl(tool, *args):
    """Run an FSL command, raising on failure."""
    cmd = [os.path.join(FSL_BIN, tool)] + [str(a) for a in args]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{tool} failed ({result.returncode}): {result.stderr or result.stdout}")
    return result


def dti_dicom_to_adc(dicom_dir, output_path):
    """
    Convert raw DTI DICOM to a masked ADC (mean diffusivity) map using:
      dcm2niix → bet (brain mask) → dtifit → MD output.
    """
    dicom_dir = Path(dicom_dir)
    output_path = Path(output_path)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp = Path(tmp_dir)
        dwi_base = str(tmp / "dwi")

        # 1) dcm2niix → 4D NIfTI + bval + bvec
        subprocess.run(
            ["dcm2niix", "-z", "y", "-f", "dwi", "-o", str(tmp), str(dicom_dir)],
            capture_output=True, text=True, check=True,
        )

        dwi_nii = tmp / "dwi.nii.gz"
        bval = tmp / "dwi.bval"
        bvec = tmp / "dwi.bvec"

        if not dwi_nii.exists():
            candidates = sorted(tmp.glob("*.nii.gz"))
            if not candidates:
                raise ValueError(f"dcm2niix produced no .nii.gz for {dicom_dir}")
            dwi_nii = candidates[0]
            stem = dwi_nii.stem.replace(".nii", "")
            bval = tmp / f"{stem}.bval"
            bvec = tmp / f"{stem}.bvec"

        for f in [dwi_nii, bval, bvec]:
            if not f.exists():
                raise FileNotFoundError(f"Missing expected file: {f}")

        # 2) bet — brain extraction
        brain_base = str(tmp / "dwi_brain")
        _fsl("bet", dwi_nii, brain_base, "-m", "-f", "0.3")
        mask = tmp / "dwi_brain_mask.nii.gz"

        # 3) dtifit — tensor fit, produces *_MD.nii.gz (= ADC)
        dti_base = str(tmp / "dti")
        _fsl("dtifit",
             "-k", dwi_nii,
             "-o", dti_base,
             "-m", mask,
             "-r", bvec,
             "-b", bval)

        md_nii = tmp / "dti_MD.nii.gz"
        if not md_nii.exists():
            raise FileNotFoundError(f"dtifit did not produce MD map for {dicom_dir}")

        # 5) Copy MD → output as uncompressed .nii
        img = nib.load(md_nii)
        nib.save(nib.Nifti1Image(img.get_fdata().astype(np.float32), img.affine, img.header),
                 str(output_path))

In [24]:
dti_base_dir = Path("model_data/adni/dti_long_data/dti_long_dcm")
dti_output_dir = Path("model_data/adni/dti_long_data/dti_long_raw")

In [25]:
dti_i_folders = sorted(
    [
        f
        for f in dti_base_dir.rglob("I*")
        if f.is_dir() and (any(f.glob("*.dcm")) or any(f.glob("*.DCM")))
    ],
    key=lambda p: str(p),
)

In [26]:
# Test on first DTI scan only
test_folder = dti_i_folders[0]
image_id = test_folder.name
subject_id = test_folder.relative_to(dti_base_dir).parts[0]
test_out = dti_output_dir / f"{image_id}_{subject_id}_TEST_MD.nii"

print(f"Input:  {test_folder}")
print(f"Output: {test_out}")

dti_dicom_to_adc(test_folder, test_out)

md = nib.load(test_out)
data = md.get_fdata()
print(f"MD shape: {data.shape}")
print(f"MD min={float(np.nanmin(data)):.6e}, max={float(np.nanmax(data)):.6e}")

Input:  model_data/adni/dti_long_data/dti_long_dcm/002_S_0413/Axial_DTI/2017-06-21_13_48_54.0/I863064
Output: model_data/adni/dti_long_data/dti_long_raw/I863064_002_S_0413_TEST_MD.nii
MD shape: (116, 116, 80)
MD min=-3.804509e-03, max=4.047291e-03

In [27]:
# Batch: all I* folders → dti_long_raw (skip if output already exists)
dti_errors = 0
for i_folder in tqdm(dti_i_folders, desc="DTI DICOM → ADC"):
    image_id = i_folder.name
    subject_id = i_folder.relative_to(dti_base_dir).parts[0]
    output_path = dti_output_dir / f"{image_id}_{subject_id}.nii"
    if output_path.exists():
        continue
    try:
        dti_dicom_to_adc(i_folder, output_path)
    except Exception as e:
        print(f"\nError processing {i_folder}: {e}")
        dti_errors += 1

print(f"\nDone. Errors: {dti_errors}")

DTI DICOM → ADC:  74%|███████▍  | 595/802 [1:43:10<1:21:00, 23.48s/it]

Error processing model_data/adni/dti_long_data/dti_long_dcm/128_S_0205/Axial_DTI/2022-08-04_10_30_38.0/I1612816: Missing expected file: /var/folders/4r/2w_vg8k91mldqsvxyw1y1cnml0bjbd/T/tmp8l_erus0/dwi.bval

DTI DICOM → ADC: 100%|██████████| 802/802 [2:28:14<00:00, 11.09s/it]

Done. Errors: 1

In [35]:
dti_raw_dir = Path("model_data/adni/dti_long_data/dti_long_raw")
dti_reg_dir = Path("model_data/adni/dti_long_data/dti_long_registered")
t1_reg_dir = Path("model_data/adni/t1_long_data/t1_long_registered")

dti_nii_files = sorted(f for f in os.listdir(dti_raw_dir) if f.endswith(".nii"))

In [36]:
# Build lookup: subject_id → list of registered T1 filenames
t1_by_subject = {}
for t1f in os.listdir(t1_reg_dir):
    if not t1f.endswith(".nii"):
        continue
    sid = t1f.split("_", 1)[1].replace(".nii", "")
    t1_by_subject.setdefault(sid, []).append(t1f)

In [38]:
dti_reg_errors = 0
dti_reg_skipped = 0

for fname in tqdm(dti_nii_files, desc="Register DTI ADC to subject T1 (MNI)"):
    out_path = dti_reg_dir / fname
    if out_path.exists():
        continue

    subject_id = fname.split("_", 1)[1].replace(".nii", "")
    t1_candidates = t1_by_subject.get(subject_id)
    if not t1_candidates:
        dti_reg_skipped += 1
        continue

    try:
        fixed_t1 = ants.image_read(str(t1_reg_dir / t1_candidates[0]))
        moving_dti = ants.image_read(str(dti_raw_dir / fname))
        reg = ants.registration(fixed=fixed_t1, moving=moving_dti, type_of_transform="Rigid")
        ants.image_write(reg["warpedmovout"], str(out_path))
    except Exception as e:
        print(f"\nError registering {fname}: {e}")
        dti_reg_errors += 1

print(f"\nDone. Errors: {dti_reg_errors}, Skipped (no matching T1): {dti_reg_skipped}")

Register DTI ADC to subject T1 (MNI):  16%|█▌        | 130/801 [01:34<07:57,  1.40it/s]Exception Object caught:

itk::ExceptionObject (0x3119ef8e0)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31ab15c00): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1092244_114_S_6039.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  28%|██▊       | 223/801 [02:38<06:41,  1.44it/s]Exception Object caught:

itk::ExceptionObject (0x12a1f0d40)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31ab15c00): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1224877_020_S_6513.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  31%|███       | 245/801 [02:53<06:08,  1.51it/s]Exception Object caught:

itk::ExceptionObject (0x3119ef8e0)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31028cfe0): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1241880_020_S_5203.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  35%|███▌      | 282/801 [03:19<07:38,  1.13it/s]Exception Object caught:

itk::ExceptionObject (0x10959dd90)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31332ac10): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1278648_020_S_6185.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  39%|███▉      | 316/801 [03:41<05:52,  1.38it/s]Exception Object caught:

itk::ExceptionObject (0x31ab16f70)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31ab20600): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1325865_020_S_6449.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  40%|███▉      | 318/801 [03:42<04:24,  1.82it/s]Exception Object caught:

itk::ExceptionObject (0x3112ca6f0)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x312e384d0): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1329976_020_S_6513.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  40%|████      | 321/801 [03:44<04:12,  1.90it/s]Exception Object caught:

itk::ExceptionObject (0x313515300)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x310c9cb20): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1332415_020_S_6227.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  42%|████▏     | 335/801 [03:52<05:02,  1.54it/s]Exception Object caught:

itk::ExceptionObject (0x312e49df0)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x311b0c7f0): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1349126_020_S_6504.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  44%|████▍     | 356/801 [04:05<04:39,  1.59it/s]Exception Object caught:

itk::ExceptionObject (0x106973f10)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x3133498c0): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1412031_020_S_6901.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  45%|████▌     | 364/801 [04:10<04:57,  1.47it/s]Exception Object caught:

itk::ExceptionObject (0x3102a2130)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x17f1e0b60): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1428968_022_S_5004.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  46%|████▌     | 366/801 [04:11<03:40,  1.97it/s]Exception Object caught:

itk::ExceptionObject (0x310c7c660)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x17f1c2d50): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1430355_022_S_2263.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  59%|█████▉    | 476/801 [05:27<03:48,  1.42it/s]Exception Object caught:

itk::ExceptionObject (0x31350b170)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31332ac10): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I1653105_114_S_6524.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  72%|███████▏  | 577/801 [06:47<03:03,  1.22it/s]Exception Object caught:

itk::ExceptionObject (0x17f1e28c0)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x310c9cb20): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I879213_114_S_6039.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI):  83%|████████▎ | 661/801 [07:50<01:47,  1.30it/s]Exception Object caught:

itk::ExceptionObject (0x3102a2130)
Location: "unknown"
File: /Users/runner/work/ANTsPy/ANTsPy/itksource/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
Line: 124
Description: ITK ERROR: ImageMomentsCalculator(0x31ab23cf0): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

Error registering I923015_114_S_6057.nii: Registration failed with error code 1

Register DTI ADC to subject T1 (MNI): 100%|██████████| 801/801 [09:34<00:00,  1.39it/s]

Done. Errors: 14, Skipped (no matching T1): 0